import type {
  Category,
  HomeFeedSection,
  LearningPath,
  ScenarioChecklist,
  ScenarioDetail,
  ScenarioFaq,
  ScenarioQuiz,
  ScenarioScript,
  ScenarioStep,
  SimulatorScenario,
  TargetStage,
  ToolkitResource,
} from "../types/young-study";

type ScenarioSeedInput = {
  slug: string;
  title: string;
  categorySlug: string;
  summary: string;
  oneLiner: string;
  targetUsers: string[];
  targetStages: TargetStage[];
  difficulty: ScenarioDetail["difficulty"];
  estimatedMinutes: number;
  emergencyLevel: number;
  isFeatured: boolean;
  starterPriority: number;
  popularityScore: number;
  coverStyle: string;
  aliases?: string[];
  keywords?: string[];
  tags?: string[];
  whatYouWillLearn?: string[];
  preparationItems: string[];
  steps: Array<{ title: string; body: string; tip?: string }>;
  commonPitfalls: string[];
  keyQuestions: string[];
  faqItems?: Array<{ question: string; answer: string }>;
  scripts?: Array<{ title: string; content: string; scriptType?: ScenarioScript["scriptType"] }>;
  checklistTitle?: string;
  checklistItems?: string[];
  quiz?: {
    question: string;
    options: string[];
    correctAnswer: number;
    explanation: string;
  };
  relatedScenarioSlugs?: string[];
};

export const STAGE_LABELS: Record<TargetStage, string> = {
  freshman: "大一新生",
  independent: "独立生活",
  intern: "第一次实习",
  graduate: "毕业找工作",
  "new-city": "陌生城市",
};

export const DIFFICULTY_LABELS: Record<ScenarioDetail["difficulty"], string> = {
  easy: "先上手",
  standard: "常用场景",
  watchout: "重点避坑",
};

export const categories: Category[] = [
  {
    id: "life-admin",
    name: "生活办事",
    slug: "life-admin",
    icon: "NotebookPen",
    description: "日常办事、寄件、洗护这些第一次最容易犯怵的小事。",
    sortOrder: 1,
    accent: "peach",
  },
  {
    id: "transport",
    name: "出行交通",
    slug: "transport",
    icon: "TrainFront",
    description: "从买票到进站再到落地，帮你把第一次出门这条线走顺。",
    sortOrder: 2,
    accent: "sky",
  },
  {
    id: "jobs",
    name: "求职就业",
    slug: "jobs",
    icon: "BriefcaseBusiness",
    description: "工资、社保、三方协议、面试这些进入职场前后的关键知识。",
    sortOrder: 3,
    accent: "mint",
  },
  {
    id: "housing",
    name: "租房住房",
    slug: "housing",
    icon: "House",
    description: "租房前怎么选、入住后怎么确认、退租时怎么留证。",
    sortOrder: 4,
    accent: "sand",
  },
  {
    id: "finance",
    name: "金融与支付",
    slug: "finance",
    icon: "WalletCards",
    description: "银行卡、ATM、工资条和费用优化这些钱相关的第一课。",
    sortOrder: 5,
    accent: "lime",
  },
  {
    id: "medical-emergency",
    name: "医疗与应急",
    slug: "medical-emergency",
    icon: "Cross",
    description: "看病、医保、报警、急救这些慌的时候更需要一眼看懂。",
    sortOrder: 6,
    accent: "rose",
  },
  {
    id: "rights",
    name: "社会规则与维权",
    slug: "rights",
    icon: "ShieldAlert",
    description: "面对快递、用工、押金这些纠纷，先知道怎么留证和怎么说。",
    sortOrder: 7,
    accent: "amber",
  },
  {
    id: "city-survival",
    name: "城市生存",
    slug: "city-survival",
    icon: "Map",
    description: "去陌生城市读书、实习、工作时，先把最重要的几步踩稳。",
    sortOrder: 8,
    accent: "ocean",
  },
  {
    id: "campus-transition",
    name: "校园到社会过渡",
    slug: "campus-transition",
    icon: "GraduationCap",
    description: "刚离开家、刚离开校园时最需要的一批基础生存技能。",
    sortOrder: 9,
    accent: "violet",
  },
];

const categoryMap = new Map(categories.map((item) => [item.slug, item]));

function normalizeActionTitle(title: string) {
  return title
    .replace(/^如何/, "")
    .replace(/^什么是/, "")
    .replace(/^第一次/, "")
    .replace(/\s+/g, "");
}

function buildSteps(slug: string, steps: ScenarioSeedInput["steps"]): ScenarioStep[] {
  return steps.map((step, index) => ({
    id: `${slug}-step-${index + 1}`,
    title: step.title,
    body: step.body,
    tip: step.tip,
  }));
}

function buildFaqs(input: ScenarioSeedInput): ScenarioFaq[] {
  if (input.faqItems?.length) {
    return input.faqItems.map((item, index) => ({
      id: `${input.slug}-faq-${index + 1}`,
      question: item.question,
      answer: item.answer,
    }));
  }

  return [
    {
      id: `${input.slug}-faq-1`,
      question: "第一次做这件事最容易漏问什么？",
      answer: `至少先问清 ${input.keyQuestions.slice(0, 3).join("、")}。别一紧张就直接点头，先把关键信息记下来。`,
    },
    {
      id: `${input.slug}-faq-2`,
      question: "如果对方一直催我现场决定怎么办？",
      answer: "可以直接说“我是第一次处理这件事，先把信息记下来，确认后再决定”。这句话不丢人，反而能帮你把节奏拿回来。",
    },
  ];
}

function buildScripts(input: ScenarioSeedInput): ScenarioScript[] {
  if (input.scripts?.length) {
    return input.scripts.map((item, index) => ({
      id: `${input.slug}-script-${index + 1}`,
      title: item.title,
      content: item.content,
      scriptType: item.scriptType ?? (index === 0 ? "opening" : "followup"),
    }));
  }

  const action = normalizeActionTitle(input.title);

  return [
    {
      id: `${input.slug}-script-1`,
      title: "稳妥开场",
      scriptType: "opening",
      content: `你好，我是第一次${action}，想先确认一下 ${input.keyQuestions.slice(0, 2).join("、")}。你方便按顺序跟我说一下吗？`,
    },
    {
      id: `${input.slug}-script-2`,
      title: "需要缓一缓时怎么说",
      scriptType: "followup",
      content: `我先把这几个点记下来：${input.keyQuestions.slice(0, 3).join("、")}。确认完我再决定，先不着急现在拍板。`,
    },
  ];
}

function buildChecklist(input: ScenarioSeedInput): ScenarioChecklist {
  const items =
    input.checklistItems ??
    [
      ...input.preparationItems.slice(0, 2),
      ...input.keyQuestions.slice(0, 3).map((question) => `确认：${question}`),
      `做完后回头检查：${input.commonPitfalls[0]}`,
    ].slice(0, 6);

  return {
    id: `${input.slug}-checklist`,
    title: input.checklistTitle ?? `${input.title}行动清单`,
    items: items.map((content, index) => ({
      id: `${input.slug}-check-${index + 1}`,
      content,
      checkedDefault: false,
      sortOrder: index + 1,
    })),
  };
}

function buildQuiz(input: ScenarioSeedInput): ScenarioQuiz[] {
  if (input.quiz) {
    return [
      {
        id: `${input.slug}-quiz-1`,
        ...input.quiz,
      },
    ];
  }

  return [
    {
      id: `${input.slug}-quiz-1`,
      question: "下面哪种做法更稳妥？",
      options: [
        "不好意思开口，什么都不问就先做",
        `先确认 ${input.keyQuestions[0]}，再决定下一步`,
        "对方说什么都先答应，回头再想",
      ],
      correctAnswer: 1,
      explanation: input.oneLiner,
    },
  ];
}

function buildWhatYouWillLearn(input: ScenarioSeedInput) {
  if (input.whatYouWillLearn?.length) {
    return input.whatYouWillLearn;
  }

  return [
    `先搞清楚 ${input.steps[0]?.title ?? "第一步"} 应该怎么做`,
    `知道现场至少要确认 ${input.keyQuestions.slice(0, 2).join("、")}`,
    `遇到 ${input.commonPitfalls[0]} 这类坑时别急着往下走`,
  ];
}

function createScenario(input: ScenarioSeedInput): ScenarioDetail {
  const category = categoryMap.get(input.categorySlug);

  if (!category) {
    throw new Error(`Unknown category: ${input.categorySlug}`);
  }

  const steps = buildSteps(input.slug, input.steps);
  const faqs = buildFaqs(input);
  const scripts = buildScripts(input);
  const checklist = buildChecklist(input);
  const quiz = buildQuiz(input);
  const whatYouWillLearn = buildWhatYouWillLearn(input);

  return {
    id: input.slug,
    title: input.title,
    slug: input.slug,
    categorySlug: category.slug,
    categoryName: category.name,
    summary: input.summary,
    oneLiner: input.oneLiner,
    targetUsers: input.targetUsers,
    targetStages: input.targetStages,
    difficulty: input.difficulty,
    estimatedMinutes: input.estimatedMinutes,
    emergencyLevel: input.emergencyLevel,
    isFeatured: input.isFeatured,
    starterPriority: input.starterPriority,
    popularityScore: input.popularityScore,
    coverStyle: input.coverStyle,
    aliases: input.aliases ?? [],
    keywords: input.keywords ?? [],
    tags: input.tags ?? [],
    whatYouWillLearn,
    preparationItems: input.preparationItems,
    steps,
    pitfallItems: input.commonPitfalls,
    faqs,
    scripts,
    checklist,
    quiz,
    relatedScenarioSlugs: input.relatedScenarioSlugs ?? [],
    sections: [
      {
        id: `${input.slug}-section-intro`,
        sectionType: "intro",
        title: "先知道这件事是什么",
        content: [input.summary, input.oneLiner, ...whatYouWillLearn],
        sortOrder: 1,
      },
      {
        id: `${input.slug}-section-prep`,
        sectionType: "preparation",
        title: "去之前先准备",
        content: input.preparationItems,
        sortOrder: 2,
      },
      {
        id: `${input.slug}-section-steps`,
        sectionType: "steps",
        title: "按这个顺序做",
        content: steps,
        sortOrder: 3,
      },
      {
        id: `${input.slug}-section-pitfalls`,
        sectionType: "pitfalls",
        title: "这些坑别硬踩",
        content: input.commonPitfalls,
        sortOrder: 4,
      },
      {
        id: `${input.slug}-section-faq`,
        sectionType: "faq",
        title: "常见问题",
        content: faqs,
        sortOrder: 5,
      },
      {
        id: `${input.slug}-section-scripts`,
        sectionType: "scripts",
        title: "真实话术模板",
        content: scripts,
        sortOrder: 6,
      },
      {
        id: `${input.slug}-section-checklist`,
        sectionType: "checklist",
        title: checklist.title,
        content: checklist,
        sortOrder: 7,
      },
      {
        id: `${input.slug}-section-quiz`,
        sectionType: "quiz",
        title: "学完自测",
        content: quiz,
        sortOrder: 8,
      },
    ],
  };
}

const scenarioInputsPart1: ScenarioSeedInput[] = [
  {
    slug: "how-to-get-phone-card",
    title: "如何办手机卡",
    categorySlug: "campus-transition",
    summary: "第一次办手机卡，重点不是听谁声音大，而是先问清月租、流量、合约期和销户方式。",
    oneLiner: "别被“学生专属”“今天最后一天”这种话带跑，先把套餐细节问清楚。",
    targetUsers: ["刚入学的大一新生", "第一次自己去营业厅办业务的人"],
    targetStages: ["freshman", "independent", "new-city"],
    difficulty: "easy",
    estimatedMinutes: 6,
    emergencyLevel: 0,
    isFeatured: true,
    starterPriority: 97,
    popularityScore: 96,
    coverStyle: "peach",
    aliases: ["怎么办电话卡", "办流量卡"],
    keywords: ["手机卡", "电话卡", "运营商", "套餐", "流量"],
    tags: ["新手必学", "校园", "通信"],
    preparationItems: ["身份证原件", "预算上限", "想要的大概流量和通话需求"],
    steps: [
      { title: "先想清楚你要日常卡还是临时卡", body: "如果你只是短期使用，重点看是否有合约期；如果要长期用，就看月租和流量是否稳定。", tip: "别只看宣传图上的“超大流量”，很多是定向流量。" },
      { title: "到店先问四件事", body: "按顺序问月租、流量范围、合约期、销户方式。问完再让店员推荐，不要先报手机号需求就被带节奏。", tip: "把答案直接记在手机备忘录里。" },
      { title: "确认有没有附带增值业务", body: "有些套餐会默认带彩铃、会员、保险、宽带之类的附加项，办之前就要问是不是能取消。", tip: "看到“首月免费”要继续追问次月怎么收费。" },
      { title: "办完当场核对短信和 App", body: "确认套餐名称、月租金额和首月费用，发现和口头说法不一样，现场就提出来。", tip: "别等回宿舍才看短信。" },
    ],
    commonPitfalls: ["被默认开通增值业务", "没问合约期就办理导致难注销", "只听“送流量”没看长期月租"],
    keyQuestions: ["这个套餐月租以后会不会变", "有没有合约期", "不用了怎么注销"],
    relatedScenarioSlugs: ["how-to-get-bank-card", "new-city-first-24-hours"],
  },
  {
    slug: "how-to-get-bank-card",
    title: "如何办银行卡",
    categorySlug: "finance",
    summary: "第一次办银行卡，先搞清楚你要储蓄卡还是信用卡，以及有没有年费、短信通知费和转账限额。",
    oneLiner: "办卡不是越多越好，先办一张稳定好用、网银顺手的储蓄卡就够了。",
    targetUsers: ["第一次办银行卡的大学生", "刚实习需要工资卡的人"],
    targetStages: ["freshman", "intern", "graduate"],
    difficulty: "easy",
    estimatedMinutes: 7,
    emergencyLevel: 0,
    isFeatured: true,
    starterPriority: 95,
    popularityScore: 93,
    coverStyle: "lime",
    aliases: ["办工资卡", "办储蓄卡"],
    keywords: ["银行卡", "储蓄卡", "工资卡", "限额", "年费"],
    tags: ["金融", "新手必学"],
    preparationItems: ["身份证原件", "常用手机号", "学校或公司要求的开户信息（如果有）"],
    steps: [
      { title: "先确定你这次办的是储蓄卡", body: "多数学生和刚工作的人先办储蓄卡就够了，信用卡不是新手刚需。", tip: "如果公司指定银行，先按公司要求来。" },
      { title: "问清费用和限额", body: "重点确认有没有年费、短信通知费、跨行手续费，以及线上转账和 ATM 取现限额。", tip: "限额会直接影响你收工资或转大额房租。" },
      { title: "开通网银时别一股脑全开", body: "先开最基本的手机银行和转账功能，附带理财、保险推销都可以直接拒绝。", tip: "听不懂的项目先不勾。" },
      { title: "办完立即测试登录", body: "当场登录手机银行、改初始密码、确认绑定手机号正确，这一步能少掉很多后续折腾。", tip: "离柜前就把关键信息核对完。" },
    ],
    commonPitfalls: ["把储蓄卡和信用卡混着办", "没注意短信通知费和年费", "被顺手开通一堆并不需要的附加服务"],
    keyQuestions: ["这张卡有没有年费或短信通知费", "手机银行怎么开通", "线上转账限额是多少"],
    relatedScenarioSlugs: ["atm-deposit-withdrawal", "read-first-pay-slip"],
  },
  {
    slug: "check-utilities",
    title: "如何查水电费",
    categorySlug: "life-admin",
    summary: "第一次独立生活最常见的慌张时刻之一，就是不知道水电费去哪查、怎么确认有没有欠费。",
    oneLiner: "先问清缴费主体和账号，再去 App、物业或小程序查，不要等断电了才找入口。",
    targetUsers: ["第一次住宿舍外或租房的人", "刚搬进新地方的人"],
    targetStages: ["independent", "new-city", "freshman"],
    difficulty: "easy",
    estimatedMinutes: 5,
    emergencyLevel: 0,
    isFeatured: false,
    starterPriority: 84,
    popularityScore: 82,
    coverStyle: "peach",
    aliases: ["怎么看水电费", "怎么查电费"],
    keywords: ["水费", "电费", "物业", "缴费户号"],
    tags: ["独立生活", "租房"],
    preparationItems: ["住址信息", "缴费户号或房东提供的账户信息", "手机支付方式"],
    steps: [
      { title: "先确认谁在收这笔钱", body: "有的房子是国家电网或水务公司直缴，有的是物业代收，还有的是房东转收。先问清楚，否则入口都找错。", tip: "问清“是官方缴费还是转账给房东”。" },
      { title: "拿到账号后再查余额", body: "有了户号、房号或绑定手机号，再去对应 App、小程序或物业窗口查余额和历史账单。", tip: "没有账号就不要盲目搜一堆小程序。" },
      { title: "核对计费方式", body: "看是按民水民电、商业水电还是分摊收费，差别很大。租房时这件事必须尽早问。", tip: "商业水电通常更贵。" },
      { title: "设置提醒，别临停才补", body: "把常用缴费入口收藏起来，最好在月底固定查一次。", tip: "第一次独居最省心的办法就是把入口记住。" },
    ],
    commonPitfalls: ["连缴费主体都没搞清楚", "商业水电和民水民电没问明白", "没有保留缴费记录"],
    keyQuestions: ["这套房水电费由谁收", "缴费账号是什么", "收费标准按什么算"],
    relatedScenarioSlugs: ["pay-rent-utilities", "how-to-rent-house"],
  },
  {
    slug: "wash-clothes",
    title: "如何洗衣服",
    categorySlug: "life-admin",
    summary: "洗衣服看起来像小事，但第一次独立生活时最容易把浅色染坏、把羊毛洗缩、把衣服越洗越脏。",
    oneLiner: "先分颜色、看洗标、口袋掏空，洗衣机就不会被你当成抽奖机。",
    targetUsers: ["刚离家独立生活的人", "宿舍洗衣服全靠试错的人"],
    targetStages: ["freshman", "independent"],
    difficulty: "easy",
    estimatedMinutes: 4,
    emergencyLevel: 0,
    isFeatured: false,
    starterPriority: 78,
    popularityScore: 80,
    coverStyle: "mint",
    aliases: ["洗衣机怎么用", "衣服怎么洗"],
    keywords: ["洗衣服", "洗衣机", "洗标", "染色"],
    tags: ["独立生活", "宿舍"],
    preparationItems: ["脏衣服", "洗衣液", "晾衣架或烘干条件"],
    steps: [
      { title: "先分颜色和材质", body: "白色、浅色和深色分开；毛衣、羽绒服、贴膜印花衣服先看洗标。", tip: "第一次最容易因为偷懒混洗而翻车。" },
      { title: "口袋掏空再洗", body: "纸巾、耳机、卡片、硬币都要拿出来，尤其纸巾会把整桶衣服洗成雪花。", tip: "洗之前花 30 秒检查，比重洗一桶轻松多了。" },
      { title: "洗衣液别倒太多", body: "洗衣液不是越多越干净，过量反而会残留。普通日常衣物选标准模式就够。", tip: "不懂模式时优先选“标准/日常”。" },
      { title: "洗完尽快晾", body: "衣服洗完别闷在桶里太久，不然容易有味道。", tip: "深色衣服尽量翻面晾，褪色会慢一点。" },
    ],
    commonPitfalls: ["深浅色混洗导致串色", "纸巾没掏干净", "洗完长时间不晾导致发臭"],
    keyQuestions: ["这件衣服能不能机洗", "需不需要分开洗", "洗完在哪里晾更合适"],
    relatedScenarioSlugs: ["wash-underwear", "first-independent-living-guide"],
  },
  {
    slug: "wash-underwear",
    title: "如何洗内裤",
    categorySlug: "life-admin",
    summary: "内裤这件事别嫌小题大做，洗法不对容易有异味，也容易和别的衣服混在一起不卫生。",
    oneLiner: "单独洗、尽快洗、彻底晾干，比什么神奇洗护产品都更重要。",
    targetUsers: ["第一次自己处理贴身衣物的人"],
    targetStages: ["freshman", "independent"],
    difficulty: "easy",
    estimatedMinutes: 3,
    emergencyLevel: 0,
    isFeatured: false,
    starterPriority: 70,
    popularityScore: 72,
    coverStyle: "sand",
    aliases: ["内裤怎么洗"],
    keywords: ["内裤", "手洗", "晾干", "卫生"],
    tags: ["独立生活"],
    preparationItems: ["中性洗衣液或肥皂", "清水", "通风晾晒位置"],
    steps: [
      { title: "尽量当天洗", body: "别把贴身衣物堆很多天再处理，时间越久越容易有味道。", tip: "洗的动作其实很快，拖延会更麻烦。" },
      { title: "单独清洗", body: "最好别和袜子、外衣一起洗，手洗最稳妥。", tip: "如果一定机洗，也尽量放洗衣袋。" },
      { title: "重点洗裆部和边缘", body: "轻搓重点位置就够，不用暴力揉。", tip: "洗涤剂残留也会不舒服，所以最后冲洗要彻底。" },
      { title: "彻底晾干再收", body: "没干透就收起来容易返潮有味。", tip: "潮湿天气优先放通风处，不要闷着。" },
    ],
    commonPitfalls: ["和袜子混洗", "洗完没冲净", "没晒干就收起来"],
    keyQuestions: ["是不是单独洗", "有没有彻底冲干净", "收纳前是不是完全干了"],
    relatedScenarioSlugs: ["wash-clothes", "first-independent-living-guide"],
  },
  {
    slug: "send-courier",
    title: "如何寄快递",
    categorySlug: "life-admin",
    summary: "寄快递最怕的是到了驿站才发现没包装、没量尺寸、报价听不懂。",
    oneLiner: "先问清运费怎么算、保价怎么选、到付还是现付，再决定寄哪家。",
    targetUsers: ["第一次自己寄件的人", "毕业搬宿舍的人"],
    targetStages: ["freshman", "independent", "graduate"],
    difficulty: "easy",
    estimatedMinutes: 5,
    emergencyLevel: 0,
    isFeatured: true,
    starterPriority: 85,
    popularityScore: 88,
    coverStyle: "sky",
    aliases: ["怎么寄包裹"],
    keywords: ["快递", "寄件", "保价", "到付"],
    tags: ["日常办事"],
    preparationItems: ["收件人姓名电话地址", "待寄物品", "大概重量和尺寸"],
    steps: [
      { title: "先确认能不能寄", body: "液体、易碎、锂电池这类物品规则不一样，先问门店或小程序。", tip: "寄不了的东西别到了现场才翻包。" },
      { title: "准备完整收件信息", body: "姓名、电话、详细地址、门牌号最好一次性写对。", tip: "地址错一个字，补救成本都很高。" },
      { title: "问清价格和保价", body: "问运费按重量还是体积算，是否需要额外包装费，贵重物品要不要保价。", tip: "贵重物品别只图便宜。" },
      { title: "寄出后保留底单", body: "快递单号、称重照片、门店聊天记录都留一下，后面丢件时很有用。", tip: "底单随手拍一张。" },
    ],
    commonPitfalls: ["收件信息不完整", "没问保价就寄贵重物品", "寄完没留底单"],
    keyQuestions: ["运费怎么算", "保价怎么赔", "这个物品能不能寄"],
    relatedScenarioSlugs: ["courier-lost-claim", "new-city-first-24-hours"],
  },
  {
    slug: "courier-lost-claim",
    title: "快递丢失怎么维权",
    categorySlug: "rights",
    summary: "快递丢了最重要的不是先吵，而是先把订单、重量、价值、物流时间线留好证据。",
    oneLiner: "先找平台和快递公司登记，再按时间线催处理，证据别散。",
    targetUsers: ["遇到丢件、少件、误签的人"],
    targetStages: ["independent", "intern", "new-city"],
    difficulty: "watchout",
    estimatedMinutes: 8,
    emergencyLevel: 1,
    isFeatured: true,
    starterPriority: 83,
    popularityScore: 90,
    coverStyle: "amber",
    aliases: ["快递丢了怎么办", "丢件投诉"],
    keywords: ["快递丢失", "维权", "投诉", "赔偿"],
    tags: ["紧急处理", "维权"],
    preparationItems: ["订单截图", "快递单号", "商品价值证明", "和客服沟通记录"],
    steps: [
      { title: "先固定证据", body: "把订单详情、物流轨迹、商品金额、聊天记录先截全。", tip: "越早截图越好，别等页面更新后找不到。" },
      { title: "同时找平台和快递公司", body: "在电商平台发起售后，同时联系快递公司客服登记丢件。", tip: "只找其中一边，处理会慢很多。" },
      { title: "问清理赔时限和材料", body: "确认需要提供哪些证据、多久给回复、按什么标准赔。", tip: "把客服工号或工单号记下来。" },
      { title: "久拖不决就升级投诉", body: "超过承诺时限没结果，就继续向平台、官方客服或邮政申诉渠道升级。", tip: "升级投诉时带着完整时间线说话。" },
    ],
    commonPitfalls: ["只口头投诉不留证据", "没有保存商品价值证明", "被一句“再等等”拖很久"],
    keyQuestions: ["赔偿按什么标准算", "多久给结果", "需要补哪些证据"],
    faqItems: [
      { question: "只赔运费正常吗？", answer: "不一定。是否只赔运费，要看有没有保价、商品价值证明是否充足，以及平台和快递公司的规则。别听对方一句话就结束。" },
      { question: "我该先找商家还是快递？", answer: "电商单优先同步找商家/平台和快递，别只找一边。你需要的是有人接住责任，而不是在几方之间来回踢。" },
    ],
    scripts: [
      {
        title: "给客服的维权开场",
        scriptType: "complaint",
        content: "你好，这个订单现在已经超过正常时效且物流停滞/显示签收但我没有收到。我这边已经整理了订单截图、物流轨迹和商品金额，请帮我登记丢件并告知理赔流程和时限。",
      },
      {
        title: "被拖延时的跟进话术",
        scriptType: "followup",
        content: "上次你们承诺的处理时间已经到了，我现在需要明确回复：这单目前责任归属、赔偿标准和最终答复时间分别是什么？请不要只回复“再等等”。",
      },
    ],
    checklistTitle: "快递丢失维权清单",
    checklistItems: ["截图订单详情", "截图物流轨迹", "保存商品金额证明", "记录客服工单号", "超过时限继续升级投诉"],
    relatedScenarioSlugs: ["send-courier", "call-police"],
  },
  {
    slug: "lower-phone-bill",
    title: "如何降低话费",
    categorySlug: "finance",
    summary: "很多人的话费高，不是因为用得多，而是旧套餐没换、增值业务没关、自动续费没注意。",
    oneLiner: "先看账单，再找出“月租”“增值业务”“自动续费”这三块最容易漏的钱。",
    targetUsers: ["每个月都觉得话费离谱的人"],
    targetStages: ["freshman", "independent", "intern"],
    difficulty: "standard",
    estimatedMinutes: 5,
    emergencyLevel: 0,
    isFeatured: false,
    starterPriority: 68,
    popularityScore: 76,
    coverStyle: "lime",
    aliases: ["话费太贵怎么办"],
    keywords: ["话费", "套餐", "自动续费", "增值业务"],
    tags: ["省钱"],
    preparationItems: ["运营商 App", "近三个月账单", "当前套餐名称"],
    steps: [
      { title: "先看最近几个月账单", body: "别只看本月总金额，要看明细里哪些项目一直在扣。", tip: "尤其留意看不懂的小额项目。" },
      { title: "找出旧套餐和附加项", body: "看月租是不是偏高，有没有不再用的会员、彩铃、流量包。", tip: "许多钱不是大头，而是小额长期扣。" },
      { title: "比价再换套餐", body: "在官方 App 看当前可选套餐，不要只听线下店员推荐。", tip: "能线上改就优先线上改，信息更清楚。" },
      { title: "改完后看下月账单", body: "套餐更改不代表马上不扣费，下个月再核对一次。", tip: "确认旧增值业务是否真的关闭。" },
    ],
    commonPitfalls: ["没看明细只看总数", "旧业务没完全取消", "为了便宜换成不适合自己的套餐"],
    keyQuestions: ["哪些项目每个月都在扣", "有没有不需要的增值业务", "换套餐后什么时候生效"],
    relatedScenarioSlugs: ["how-to-get-phone-card", "read-first-pay-slip"],
  },
];
const scenarioInputsPart2: ScenarioSeedInput[] = [
  {
    slug: "atm-deposit-withdrawal",
    title: "ATM 怎么存取款",
    categorySlug: "finance",
    summary: "第一次用 ATM，紧张主要来自怕按错、怕吞卡、怕周围有人盯着看。",
    oneLiner: "先确认机器是不是这家银行的，再一步一步按屏幕提示，不懂就停，不要乱点。",
    targetUsers: ["第一次自己存取款的人"],
    targetStages: ["freshman", "independent", "intern"],
    difficulty: "easy",
    estimatedMinutes: 4,
    emergencyLevel: 0,
    isFeatured: false,
    starterPriority: 72,
    popularityScore: 74,
    coverStyle: "lime",
    aliases: ["ATM怎么用"],
    keywords: ["ATM", "存钱", "取钱", "吞卡"],
    tags: ["金融"],
    preparationItems: ["银行卡", "记住的密码", "要存取的大概金额"],
    steps: [
      { title: "先看机器和周围环境", body: "尽量选银行网点内或明亮位置的 ATM，确认机器没有异常装置。", tip: "周围太拥挤就换一台。" },
      { title: "按屏幕提示操作", body: "先插卡或刷卡，再选择存款或取款。看不懂就停，不要急着乱按。", tip: "密码输入时注意遮挡。" },
      { title: "金额和回执要核对", body: "无论存还是取，确认屏幕金额和实际金额一致。", tip: "大额交易建议留回执。" },
      { title: "取卡、现金、单据一个都别漏", body: "操作结束后按顺序拿卡、拿钱、拿回执，再离开。", tip: "很多人都是最后忘拿卡。" },
    ],
    commonPitfalls: ["只拿现金忘了卡", "在陌生环境大额操作", "看不懂界面还一直硬点"],
    keyQuestions: ["这台机器是不是正规网点", "金额是否核对清楚", "有没有拿回银行卡"],
    relatedScenarioSlugs: ["how-to-get-bank-card", "new-city-first-24-hours"],
  },
  {
    slug: "choose-glasses",
    title: "如何配眼镜",
    categorySlug: "life-admin",
    summary: "第一次配眼镜最容易被一堆镜片名词和套餐价绕晕，最后多花钱还不一定适合。",
    oneLiner: "先验光，再问镜片度数、折射率、价格和售后，别一上来只看镜框好不好看。",
    targetUsers: ["第一次配眼镜的人", "准备换镜片的人"],
    targetStages: ["freshman", "independent"],
    difficulty: "standard",
    estimatedMinutes: 6,
    emergencyLevel: 0,
    isFeatured: false,
    starterPriority: 62,
    popularityScore: 69,
    coverStyle: "peach",
    aliases: ["配眼镜怎么问"],
    keywords: ["配眼镜", "验光", "镜片", "镜框"],
    tags: ["生活办事"],
    preparationItems: ["旧眼镜（有的话）", "大概预算", "近视度数变化感受"],
    steps: [
      { title: "先验光，不急着选框", body: "先确认当前度数和散光情况，再决定镜片和镜框。", tip: "别跳过验光直接照旧配。" },
      { title: "问清镜片参数", body: "重点问折射率、是否防蓝光、是否有额外镀膜、价格差别在哪里。", tip: "听不懂时让对方直接说“适合什么人”。" },
      { title: "试戴看舒适度", body: "镜框不只看颜值，还要看鼻托、重量和压不压耳朵。", tip: "低头时容易滑的镜框，平时会很烦。" },
      { title: "确认售后和复查", body: "问清调整、换鼻托、螺丝松了能不能免费处理。", tip: "售后比一时便宜更重要。" },
    ],
    commonPitfalls: ["只看外观不看镜片参数", "听到防蓝光就默认更好", "没问售后就下单"],
    keyQuestions: ["这副镜片适合我的度数吗", "价格差别主要差在哪", "售后能做哪些调整"],
    relatedScenarioSlugs: ["new-city-survival-guide", "first-independent-living-guide"],
  },
  {
    slug: "how-to-rent-house",
    title: "如何租房",
    categorySlug: "housing",
    summary: "第一次租房最怕的是看房时只看装修和拍照角度，签完才发现水电贵、隔音差、押金难退。",
    oneLiner: "先算预算，再看房，再核对合同和费用，别把顺序颠倒。",
    targetUsers: ["第一次独自租房的人", "来外地实习或工作的年轻人"],
    targetStages: ["independent", "intern", "graduate", "new-city"],
    difficulty: "watchout",
    estimatedMinutes: 12,
    emergencyLevel: 1,
    isFeatured: true,
    starterPriority: 99,
    popularityScore: 98,
    coverStyle: "sand",
    aliases: ["第一次租房"],
    keywords: ["租房", "看房", "合同", "押金", "中介费"],
    tags: ["高频", "避坑", "新手必学"],
    whatYouWillLearn: ["先把预算和通勤边界算清楚", "看房时重点看采光、隔音、水电和维修责任", "签合同前知道哪些条款一定要逐条确认"],
    preparationItems: ["预算范围", "通勤时长上限", "身份证和支付方式", "看房时拍照留证的手机"],
    steps: [
      { title: "先定预算和通勤边界", body: "别先刷房源刷到上头，先算每月能承受的房租和通勤上限。", tip: "房租不是唯一成本，水电网和搬家也要算进去。" },
      { title: "看房时别只看表面", body: "进门后重点看采光、潮湿、隔音、门锁、插座、水压、马桶和空调。", tip: "白天和晚上差别很大，能二次看房更稳。" },
      { title: "费用必须问细", body: "问清押几付几、中介费、物业费、水电收费标准、网费和维修责任。", tip: "听到“到时候再说”就要警惕。" },
      { title: "签约和入住都要留证", body: "签合同前拍照、签完合同再拍家具家电现状，入住前把问题点发到聊天里。", tip: "聊天记录也是证据。" },
    ],
    commonPitfalls: ["被低价房源吸引但没看隐藏成本", "签合同前没拍现状图", "水电和维修责任只口头确认"],
    keyQuestions: ["水电费按什么标准算", "押金什么时候退、怎么退", "坏了谁负责修"],
    faqItems: [
      { question: "第一次租房要不要找中介？", answer: "不是绝对不能找，而是要看你换来的是什么服务。如果只是带看和催签，收费又不透明，那就不值。" },
      { question: "租房最少要看几次？", answer: "至少一次现场看房，条件允许最好白天和晚上各看一次，或者补一轮视频核查。别只看照片下决定。" },
    ],
    scripts: [
      {
        title: "看房时的关键提问",
        scriptType: "opening",
        content: "我第一次租房，想把几件事先确认清楚：水电费怎么算、押金怎么退、平时维修谁负责、这边是否接受短租或提前解约。",
      },
      {
        title: "签合同前再确认一次",
        scriptType: "negotiation",
        content: "我想把合同里这些点逐条确认一下：费用明细、退租条件、押金退回时间、家具家电故障责任。如果和口头说法一致，我再签。",
      },
    ],
    checklistTitle: "租房检查清单",
    checklistItems: ["确认预算和通勤上限", "看房时拍采光/墙面/家具现状", "问清水电物业网费", "确认押金、中介费、维修责任", "签约后把现状发聊天留证"],
    relatedScenarioSlugs: ["rent-deposit-return", "renting-watchouts", "pay-rent-utilities", "install-broadband"],
  },
  {
    slug: "rent-deposit-return",
    title: "如何退房退押金",
    categorySlug: "housing",
    summary: "退租最怕的是搬走了才开始和房东扯皮，结果聊天记录、房屋现状、账单都不完整。",
    oneLiner: "退租不是最后一天才处理，而是从准备搬走前一周就开始留证。",
    targetUsers: ["第一次退租的人", "担心押金被乱扣的人"],
    targetStages: ["independent", "intern", "graduate", "new-city"],
    difficulty: "watchout",
    estimatedMinutes: 9,
    emergencyLevel: 1,
    isFeatured: true,
    starterPriority: 86,
    popularityScore: 88,
    coverStyle: "amber",
    aliases: ["退房押金怎么要"],
    keywords: ["退房", "押金", "退租", "留证"],
    tags: ["维权", "租房"],
    preparationItems: ["租房合同", "入住时照片和视频", "最近水电结清记录"],
    steps: [
      { title: "提前翻合同", body: "先看合同里的退租通知时间、保洁要求、钥匙交接和押金退回条款。", tip: "合同说提前 30 天通知，就别拖到最后一周。" },
      { title: "搬前先拍全屋现状", body: "和入住时的照片对照拍一遍，重点拍墙面、地板、家具、电器、水表电表。", tip: "拍视频比单张图更完整。" },
      { title: "把该结的账先结清", body: "水电网、物业、门禁卡、钥匙这些容易变成扣押金理由，能结清的先结。", tip: "把支付记录留好。" },
      { title: "交接时让对方当面确认", body: "能当面验房就当面验，不能当面也要让对方在聊天里确认收到钥匙和现状。", tip: "押金退回时间要写清楚。" },
    ],
    commonPitfalls: ["搬走后才想起拍现状", "口头退租没留文字记录", "账单没结清就等押金退回"],
    keyQuestions: ["提前多久通知退租", "押金什么时候退", "哪些情况会扣钱"],
    relatedScenarioSlugs: ["how-to-rent-house", "pay-rent-utilities"],
  },
  {
    slug: "renting-watchouts",
    title: "租房注意事项",
    categorySlug: "housing",
    summary: "如果你没时间系统学租房，这页就是压缩版避坑清单，帮你在看房和签约时先避开最容易踩的雷。",
    oneLiner: "低价、着急签、信息不透明，这三个词一旦同时出现，就先停一下。",
    targetUsers: ["准备开始看房的人"],
    targetStages: ["independent", "intern", "new-city"],
    difficulty: "standard",
    estimatedMinutes: 7,
    emergencyLevel: 1,
    isFeatured: true,
    starterPriority: 82,
    popularityScore: 84,
    coverStyle: "sand",
    aliases: ["租房避坑"],
    keywords: ["租房注意", "看房", "避坑"],
    tags: ["快速版", "避坑"],
    preparationItems: ["预算范围", "通勤路线", "看房提问清单"],
    steps: [
      { title: "先警惕离谱低价", body: "明显低于周边均价的房源，大概率有隐藏问题。", tip: "便宜本身不是错，但一定要追问为什么便宜。" },
      { title: "证件和身份要核验", body: "确认出租人身份、是否有权出租、是房东、二房东还是中介。", tip: "身份不清楚，后面纠纷会很难受。" },
      { title: "费用别只听一句总价", body: "房租之外的物业、网费、停车、卫生、维修都要问。", tip: "“包水电”也要问限额。" },
      { title: "所有关键点写进文字", body: "承诺过的事情能写进合同就写进合同，写不进去也要留聊天记录。", tip: "别只相信“放心吧”。" },
    ],
    commonPitfalls: ["只看总价不看附加费用", "没核验出租人身份", "着急签字没留文字证据"],
    keyQuestions: ["这房源是谁在出租", "除房租外还有哪些费用", "口头承诺能不能写进合同"],
    relatedScenarioSlugs: ["how-to-rent-house", "rent-deposit-return"],
  },
  {
    slug: "pay-rent-utilities",
    title: "如何交水电费",
    categorySlug: "housing",
    summary: "租房后的日常稳定感，很多时候就来自你知道每个月该交什么、去哪交、什么时候交。",
    oneLiner: "先搞清官方缴费还是房东代收，再决定你该用哪个入口。",
    targetUsers: ["刚租房入住的人"],
    targetStages: ["independent", "intern", "new-city"],
    difficulty: "easy",
    estimatedMinutes: 4,
    emergencyLevel: 0,
    isFeatured: false,
    starterPriority: 66,
    popularityScore: 67,
    coverStyle: "sand",
    aliases: ["租房怎么交水电"],
    keywords: ["交水电", "缴费", "物业", "户号"],
    tags: ["租房"],
    preparationItems: ["房东给的账户或户号", "上个月账单", "常用支付方式"],
    steps: [
      { title: "确认是不是官方缴费", body: "有的直接在电网/水务 App 交，有的是物业收，有的是房东代收。", tip: "入口错了就会一直找不到。" },
      { title: "看懂收费标准", body: "问清是民用还是商业收费，有没有公摊或物业代收。", tip: "账单不透明时不要直接转账。" },
      { title: "第一次缴费把记录留好", body: "把付款截图和账单截图放一起，以后方便核对。", tip: "尤其合租更要留记录。" },
      { title: "固定时间检查余额", body: "设个提醒，每月固定看一次。", tip: "别等停电了才着急。" },
    ],
    commonPitfalls: ["没问收费标准", "没有保存缴费记录", "把官方缴费和房东代收混在一起"],
    keyQuestions: ["收费入口在哪", "标准按什么算", "已经交了怎么留凭证"],
    relatedScenarioSlugs: ["check-utilities", "how-to-rent-house"],
  },
  {
    slug: "install-broadband",
    title: "如何办宽带",
    categorySlug: "housing",
    summary: "办宽带最容易被忽悠的是套餐年限和绑定业务，尤其一激动就签了长合约。",
    oneLiner: "先问月费、安装费、合约期和退订规则，再谈网速。",
    targetUsers: ["刚搬家需要自己装网的人"],
    targetStages: ["independent", "new-city"],
    difficulty: "standard",
    estimatedMinutes: 6,
    emergencyLevel: 0,
    isFeatured: false,
    starterPriority: 60,
    popularityScore: 66,
    coverStyle: "ocean",
    aliases: ["装宽带怎么办"],
    keywords: ["宽带", "安装费", "合约期", "退订"],
    tags: ["租房", "网络"],
    preparationItems: ["详细地址", "房东是否允许布线", "预算"],
    steps: [
      { title: "先确认房子能不能装", body: "老小区、合租房、转租房的布线条件不一样，先问房东和运营商。", tip: "别先付款后发现不能装。" },
      { title: "问清套餐和年限", body: "重点问月费、安装费、设备押金、合约期和提前退订规则。", tip: "年付便宜不一定适合短租。" },
      { title: "安装当天核对网速和设备", body: "确认光猫、路由器是谁提供的，坏了谁负责。", tip: "安装师傅走之前先简单测速。" },
      { title: "把账号和报修方式记住", body: "后面断网时最有用的是账号、报修电话和上门承诺时间。", tip: "第一次就保存下来。" },
    ],
    commonPitfalls: ["没问合约期就开通", "设备归属不清", "短租却签长合约"],
    keyQuestions: ["合约期多长", "提前退订怎么处理", "安装和设备费怎么算"],
    relatedScenarioSlugs: ["how-to-rent-house", "pay-rent-utilities"],
  },
  {
    slug: "go-to-hospital",
    title: "如何去医院看病",
    categorySlug: "medical-emergency",
    summary: "第一次独自去医院，最容易慌在不知道挂什么科、先做什么、付款在哪、结果去哪看。",
    oneLiner: "先确认症状和科室，再挂号、看诊、检查、缴费，按顺序走就没那么可怕。",
    targetUsers: ["第一次自己去医院的人", "在陌生城市看病的人"],
    targetStages: ["freshman", "independent", "new-city"],
    difficulty: "watchout",
    estimatedMinutes: 9,
    emergencyLevel: 2,
    isFeatured: true,
    starterPriority: 92,
    popularityScore: 95,
    coverStyle: "rose",
    aliases: ["医院挂号怎么弄", "第一次看病"],
    keywords: ["医院", "挂号", "科室", "看病"],
    tags: ["紧急处理", "高频"],
    whatYouWillLearn: ["不知道挂什么科时怎么先做判断", "第一次到医院时按什么顺序走", "怎么把症状说清楚，别白跑一趟"],
    preparationItems: ["身份证或医保码", "手机支付方式", "既往病历或药单（有的话）"],
    steps: [
      { title: "先判断要不要急诊", body: "如果是呼吸困难、剧烈疼痛、意识问题、出血止不住，优先急诊。一般慢性不适再走普通门诊。", tip: "不确定时先问导诊台。" },
      { title: "挂号前先确定科室", body: "不会判断科室时，先描述症状而不是上来就猜病名。", tip: "症状比自我诊断更重要。" },
      { title: "看诊时把关键信息说清", body: "什么时候开始、哪里不舒服、持续多久、有没有发烧过敏、吃过什么药，这几句先准备好。", tip: "别怕自己说得笨，医生更在意信息完整。" },
      { title: "检查和缴费按单子走", body: "医生开单后按提示去缴费、检查、拿结果，不懂就问窗口或导诊。", tip: "把所有单据和结果一起留着。" },
    ],
    commonPitfalls: ["科室没搞清就乱挂号", "症状说得太散", "检查结果没留好导致复诊重复折腾"],
    keyQuestions: ["我现在适合挂哪个科", "需不需要空腹或带资料", "检查结果去哪里看"],
    scripts: [
      {
        title: "到导诊台的求助开场",
        scriptType: "opening",
        content: "你好，我是第一次自己来看病。我的主要情况是____，从 ____ 开始，有/没有发烧和过敏。想请问我先挂哪个科比较合适？",
      },
      {
        title: "跟医生简洁说明症状",
        scriptType: "followup",
        content: "我主要是不舒服在 ____，已经持续 ____，这两天最明显的是 ____。我现在最想知道是不是需要检查、吃药或者先观察。",
      },
    ],
    relatedScenarioSlugs: ["what-is-medical-insurance", "call-ambulance", "new-city-survival-guide"],
  },
  {
    slug: "what-is-medical-insurance",
    title: "什么是医保",
    categorySlug: "medical-emergency",
    summary: "医保不是一张卡那么简单，它关心的是你有没有参保、在哪里就医、哪些项目能报、怎么结算。",
    oneLiner: "先搞清你有没有参保、参的是什么类型，再谈报销。",
    targetUsers: ["搞不清学生医保和职工医保的人", "刚开始工作的人"],
    targetStages: ["freshman", "intern", "graduate"],
    difficulty: "standard",
    estimatedMinutes: 7,
    emergencyLevel: 1,
    isFeatured: true,
    starterPriority: 80,
    popularityScore: 81,
    coverStyle: "rose",
    aliases: ["医保是什么", "医保怎么用"],
    keywords: ["医保", "报销", "学生医保", "职工医保"],
    tags: ["医疗", "基础概念"],
    preparationItems: ["医保电子凭证或社保卡", "学校或公司参保信息", "最近一次就医票据（有的话）"],
    steps: [
      { title: "先确认有没有参保", body: "没有参保就谈不上报销，先在学校、公司或当地平台确认状态。", tip: "别默认自己一定有。" },
      { title: "分清参保类型", body: "学生医保、城乡居民医保、职工医保的使用场景不完全一样。", tip: "刚毕业切换身份时要尤其注意。" },
      { title: "就医前看结算方式", body: "问清是否能直接刷医保码、是否要先自费再报。", tip: "异地就医规则更要提前问。" },
      { title: "票据和记录别乱丢", body: "如果需要后续报销，病历、发票、结算单都要留。", tip: "电子票据也要及时下载。" },
    ],
    commonPitfalls: ["以为自己参保了其实没有", "没分清学生和职工医保", "票据没留齐"],
    keyQuestions: ["我现在有没有参保", "属于哪种医保", "这次就医能不能直接结算"],
    relatedScenarioSlugs: ["go-to-hospital", "read-first-pay-slip"],
  },
];
const scenarioInputsPart3: ScenarioSeedInput[] = [
  {
    slug: "call-ambulance",
    title: "如何叫救护车",
    categorySlug: "medical-emergency",
    summary: "真正需要叫救护车时，最重要的不是说得多，而是把地点、患者状态和联系方式说准。",
    oneLiner: "先报准确位置，再说患者情况和联系电话，别只顾着重复“快来”。",
    targetUsers: ["遇到突发急症的人", "陪同他人求助的人"],
    targetStages: ["freshman", "independent", "new-city"],
    difficulty: "watchout",
    estimatedMinutes: 4,
    emergencyLevel: 3,
    isFeatured: true,
    starterPriority: 90,
    popularityScore: 86,
    coverStyle: "rose",
    aliases: ["怎么打120"],
    keywords: ["120", "救护车", "急救"],
    tags: ["紧急处理"],
    preparationItems: ["准确地址", "患者大致年龄和状态", "可接通电话的手机"],
    steps: [
      { title: "先拨打 120", body: "接通后先说准确地址，包括楼栋、单元、附近明显地标。", tip: "位置永远是第一句。" },
      { title: "再说患者状态", body: "说清是晕倒、呼吸困难、剧痛、出血还是车祸等，不用自己诊断病名。", tip: "状态比猜病因更重要。" },
      { title: "保持电话畅通", body: "如果对方要回拨确认路线，你的电话必须能打通。", tip: "不要打完就静音。" },
      { title: "有人接应更快", body: "条件允许的话安排一个人去路口或楼下接应。", tip: "电梯、门禁这些细节都能提前想一下。" },
    ],
    commonPitfalls: ["位置说不清", "只喊救命不说患者状态", "电话打完就接不到"],
    keyQuestions: ["我现在的准确位置是什么", "患者最明显的状态是什么", "还有谁能下楼接应"],
    scripts: [
      {
        title: "打 120 的信息顺序",
        scriptType: "opening",
        content: "你好，这里需要 120。位置在 ____，靠近 ____。患者现在主要情况是 ____，年龄大概 ____，我电话保持畅通，请问还需要我补充什么？",
      },
    ],
    relatedScenarioSlugs: ["go-to-hospital", "call-police"],
  },
  {
    slug: "call-police",
    title: "如何报警",
    categorySlug: "medical-emergency",
    summary: "报警时最关键的是把地点、发生了什么、有没有危险说清楚，而不是把情绪先说满。",
    oneLiner: "地点、事件、人员状态、联系方式，这四样先讲清楚。",
    targetUsers: ["遇到治安风险或突发事件的人"],
    targetStages: ["freshman", "independent", "new-city"],
    difficulty: "watchout",
    estimatedMinutes: 4,
    emergencyLevel: 3,
    isFeatured: true,
    starterPriority: 88,
    popularityScore: 84,
    coverStyle: "amber",
    aliases: ["怎么打110"],
    keywords: ["110", "报警", "派出所", "求助"],
    tags: ["紧急处理"],
    preparationItems: ["准确位置", "事件大概经过", "能接通的联系电话"],
    steps: [
      { title: "先报位置", body: "说清区、路名、门牌、楼层或明显地标。", tip: "别只说“在学校附近”。" },
      { title: "简洁描述发生了什么", body: "说清是纠纷、盗窃、骚扰、失联还是人身危险。", tip: "重点是客观、简洁。" },
      { title: "说明现场风险", body: "有没有人受伤、对方是否持械、现场是否还在继续升级。", tip: "这会影响出警判断。" },
      { title: "保留证据并等反馈", body: "通话后保留照片、视频和聊天记录，等待进一步指引。", tip: "安全优先，不要为了拍证据把自己置于危险中。" },
    ],
    commonPitfalls: ["位置说不准", "情绪很满但信息很少", "报警后没留证据"],
    keyQuestions: ["我现在具体在哪", "现场有没有正在发生的人身危险", "我手里有哪些证据"],
    relatedScenarioSlugs: ["call-ambulance", "courier-lost-claim"],
  },
  {
    slug: "food-mold-or-poisoning",
    title: "食物发霉 / 食物中毒怎么办",
    categorySlug: "medical-emergency",
    summary: "遇到疑似吃坏肚子或食物发霉，先判断症状是否严重，再决定是观察、就医还是直接急诊。",
    oneLiner: "先停吃可疑食物、保留包装，再看有没有持续呕吐、高烧、意识问题这些危险信号。",
    targetUsers: ["宿舍或租房独居的年轻人"],
    targetStages: ["freshman", "independent", "new-city"],
    difficulty: "watchout",
    estimatedMinutes: 5,
    emergencyLevel: 3,
    isFeatured: true,
    starterPriority: 79,
    popularityScore: 82,
    coverStyle: "rose",
    aliases: ["吃坏肚子怎么办", "食物中毒怎么办"],
    keywords: ["食物中毒", "发霉", "腹泻", "就医"],
    tags: ["紧急处理"],
    preparationItems: ["食物包装或剩余样本", "体温和症状记录", "可联系的同学或室友"],
    steps: [
      { title: "先停止继续吃", body: "别想着“再吃一口试试”，先停下来。", tip: "可疑食物和包装先留着。" },
      { title: "判断危险信号", body: "如果有持续呕吐、高烧、意识模糊、脱水明显、剧烈腹痛，就不要硬扛。", tip: "危险信号出现时优先就医或急诊。" },
      { title: "补充水分并观察", body: "轻症先少量多次喝水，避免继续吃刺激性食物。", tip: "不要乱吃一堆药叠加。" },
      { title: "需要时尽快就医", body: "就医时把吃过什么、什么时候开始不舒服、是否还有同伴同样症状说清楚。", tip: "把包装和拍照一起带上。" },
    ],
    commonPitfalls: ["不舒服了还继续吃", "症状明显却一直硬扛", "就医时说不清吃了什么"],
    keyQuestions: ["我有没有危险信号", "吃了什么可能有问题", "现在要观察还是去医院"],
    relatedScenarioSlugs: ["go-to-hospital", "call-ambulance"],
  },
  {
    slug: "what-is-insurance-housing-fund",
    title: "什么是五险一金",
    categorySlug: "jobs",
    summary: "很多人第一次听五险一金，只知道工资会被扣一笔，却不知道这些钱去了哪里、有什么用。",
    oneLiner: "先知道它不是公司随便扣你的钱，再看每一项分别管什么。",
    targetUsers: ["第一次接触工资单和社保的人", "刚实习转正或刚毕业的人"],
    targetStages: ["intern", "graduate"],
    difficulty: "standard",
    estimatedMinutes: 8,
    emergencyLevel: 0,
    isFeatured: true,
    starterPriority: 87,
    popularityScore: 91,
    coverStyle: "mint",
    aliases: ["五险一金是什么"],
    keywords: ["五险一金", "社保", "公积金", "工资扣款"],
    tags: ["职场基础"],
    preparationItems: ["劳动合同或 offer", "第一份工资单（有的话）", "公司给你的社保说明（有的话）"],
    steps: [
      { title: "先把五险一金拆开看", body: "养老、医疗、失业、工伤、生育和公积金，每一项对应的用途都不一样。", tip: "不要把它们混成一笔“神秘扣款”。" },
      { title: "再看谁在缴", body: "一般是个人和公司都在缴，但比例和基数要看具体规则。", tip: "这就是为什么实发工资会低于税前工资。" },
      { title: "重点看和你最有关的几项", body: "医疗和公积金通常是年轻人最先用到的，失业和养老是中长期保障。", tip: "先搞懂使用场景，比背概念更有用。" },
      { title: "遇到不明白就拿工资条对照", body: "工资条上扣了哪些、合同里写了哪些、系统里是否真的缴纳了，要对应起来看。", tip: "别只听 HR 口头说法。" },
    ],
    commonPitfalls: ["把税和五险一金混在一起", "只看扣了多少钱不看有没有实际缴上", "入职很久都没查缴费状态"],
    keyQuestions: ["公司有没有按规定给我缴", "扣的这一笔分别是什么", "我能在哪查看缴费记录"],
    relatedScenarioSlugs: ["salary-structure", "read-first-pay-slip"],
  },
  {
    slug: "salary-structure",
    title: "什么是工资结构",
    categorySlug: "jobs",
    summary: "工资结构不只是一个数字，而是基本工资、绩效、补贴、社保、公积金、个税等一整套组合。",
    oneLiner: "别只盯着“总包”或“月薪”，先问清楚哪部分稳定、哪部分浮动。",
    targetUsers: ["第一次拿 offer 的人", "实习转正或毕业入职的人"],
    targetStages: ["intern", "graduate"],
    difficulty: "standard",
    estimatedMinutes: 7,
    emergencyLevel: 0,
    isFeatured: true,
    starterPriority: 83,
    popularityScore: 88,
    coverStyle: "mint",
    aliases: ["工资结构是什么"],
    keywords: ["工资结构", "基本工资", "绩效", "补贴"],
    tags: ["职场基础"],
    preparationItems: ["offer 或劳动合同", "谈薪记录", "工资条（有的话）"],
    steps: [
      { title: "先区分固定和浮动", body: "基本工资通常更稳定，绩效、提成、奖金、补贴则要看条件。", tip: "不分清这一点，很容易误判真实收入。" },
      { title: "看发薪周期和口径", body: "月薪、年包、13 薪、季度奖说的是不同口径，别混着理解。", tip: "一旦含奖金，就要追问发放条件。" },
      { title: "把扣款也纳入结构", body: "社保、公积金、个税都会影响到手收入。", tip: "谈工资不能只谈税前数字。" },
      { title: "最后算稳定到手", body: "把大概率能拿到的钱单独算一遍，你会更清楚自己能不能承担房租和生活成本。", tip: "稳定到手才是你做预算的基准。" },
    ],
    commonPitfalls: ["把浮动绩效当成固定工资", "只看年包不看月度现金流", "没算扣款就先做支出计划"],
    keyQuestions: ["哪部分是固定收入", "绩效按什么条件发", "实发大概会是多少"],
    relatedScenarioSlugs: ["read-first-pay-slip", "what-is-insurance-housing-fund"],
  },
  {
    slug: "read-first-pay-slip",
    title: "第一次看工资条",
    categorySlug: "finance",
    summary: "第一次拿工资条，最容易只看“到手多少钱”，却不知道哪些扣款正常、哪些要追问。",
    oneLiner: "工资条不是只看最后一行，而是从应发、扣款、实发三段一起看。",
    targetUsers: ["第一次发工资的人", "发现工资和预期不一致的人"],
    targetStages: ["intern", "graduate"],
    difficulty: "standard",
    estimatedMinutes: 6,
    emergencyLevel: 0,
    isFeatured: true,
    starterPriority: 78,
    popularityScore: 85,
    coverStyle: "lime",
    aliases: ["工资条怎么看"],
    keywords: ["工资条", "应发", "实发", "扣款"],
    tags: ["钱", "职场基础"],
    preparationItems: ["工资条", "offer 或劳动合同", "考勤和请假记录"],
    steps: [
      { title: "先看应发工资", body: "确认基本工资、绩效、补贴和奖金是不是都进来了。", tip: "和 offer 里的约定对照。" },
      { title: "再看扣款项目", body: "社保、公积金、个税、考勤扣款这些都要有对应说明。", tip: "看不懂的项目要问，不丢人。" },
      { title: "最后看实发", body: "实发是应发减掉各类扣款后的结果，不是公司临时拍脑袋算的。", tip: "发现差异先找出是哪一栏不对。" },
      { title: "留一份自己的记录", body: "把每月工资条整理保存，后面申诉、换工作或办贷款时都可能用上。", tip: "电子版也要存好。" },
    ],
    commonPitfalls: ["只看最后一行实发", "发现异常却不保留工资条", "不知道差异来自哪一栏"],
    keyQuestions: ["应发和 offer 一致吗", "扣款分别是什么", "考勤和绩效有没有算对"],
    relatedScenarioSlugs: ["salary-structure", "what-is-insurance-housing-fund"],
  },
  {
    slug: "what-is-tripartite-agreement",
    title: "什么是三方协议",
    categorySlug: "jobs",
    summary: "三方协议是毕业生、学校和用人单位之间的就业协议，不等于正式劳动合同，但也不能乱签。",
    oneLiner: "签之前先搞清楚岗位、报到、违约和档案去向，别因为催签就直接点头。",
    targetUsers: ["应届毕业生", "正在签校招 offer 的人"],
    targetStages: ["graduate"],
    difficulty: "watchout",
    estimatedMinutes: 7,
    emergencyLevel: 0,
    isFeatured: true,
    starterPriority: 76,
    popularityScore: 79,
    coverStyle: "violet",
    aliases: ["三方协议是什么"],
    keywords: ["三方协议", "应届生", "校招", "违约"],
    tags: ["毕业", "求职"],
    preparationItems: ["三方协议文本", "offer 邮件", "学校就业要求"],
    steps: [
      { title: "先确认它不是劳动合同", body: "三方更像就业去向约定，后面通常还会签正式劳动合同。", tip: "别因为名字里有“协议”就以为都一样。" },
      { title: "看清岗位和报到信息", body: "岗位名称、工作地点、报到时间、是否需要培训、违约责任都要确认。", tip: "口头承诺最好落到文字。" },
      { title: "问清违约和改签规则", body: "如果后续想换工作，流程和成本是什么，要提前知道。", tip: "有些学校和单位处理方式差别很大。" },
      { title: "和家里、老师确认后再签", body: "应届生第一次签字容易被催，能留一个确认时间就留。", tip: "别被“今天不签就没了”吓住。" },
    ],
    commonPitfalls: ["把三方当成正式劳动合同", "没看违约条款", "岗位地点和口头说法不一致也照签"],
    keyQuestions: ["违约怎么处理", "报到时间和地点是否明确", "后续还要不要签劳动合同"],
    relatedScenarioSlugs: ["what-is-referral", "salary-structure"],
  },
  {
    slug: "what-is-probation",
    title: "什么是试用期",
    categorySlug: "rights",
    summary: "试用期不是公司想怎么用就怎么用，它有期限、有工资规则，也不能拿来随便压人。",
    oneLiner: "你可以不熟，但别默认试用期就等于没有权利。",
    targetUsers: ["刚入职的人", "正在被试用期规则搞得发懵的人"],
    targetStages: ["intern", "graduate"],
    difficulty: "watchout",
    estimatedMinutes: 7,
    emergencyLevel: 1,
    isFeatured: true,
    starterPriority: 82,
    popularityScore: 87,
    coverStyle: "amber",
    aliases: ["试用期是什么意思"],
    keywords: ["试用期", "工资", "转正", "劳动法"],
    tags: ["维权", "职场"],
    preparationItems: ["劳动合同", "入职通知", "考核要求或制度说明"],
    steps: [
      { title: "先看试用期写了多久", body: "试用期并不是随便定的，通常和劳动合同期限挂钩。", tip: "“先口头试试”这种说法要特别小心。" },
      { title: "再看工资怎么发", body: "试用期工资也不是想压多低就多低，至少要看是否符合约定和基本规则。", tip: "别因为新人心态就什么都不问。" },
      { title: "问清考核标准", body: "如果转正要考核，标准、周期、反馈方式最好提前知道。", tip: "模糊考核最容易被拿来卡人。" },
      { title: "出现异常及时留证", body: "聊天记录、制度截图、考核结果和工资条都要留。", tip: "维权第一步不是吵，是留证。" },
    ],
    commonPitfalls: ["以为试用期就没保障", "考核标准不清也默认接受", "出问题后没有任何证据"],
    keyQuestions: ["试用期多久", "试用期工资怎么算", "转正标准是什么"],
    relatedScenarioSlugs: ["resignation-compensation", "salary-structure"],
  },
  {
    slug: "resignation-compensation",
    title: "什么是离职赔偿",
    categorySlug: "rights",
    summary: "离职赔偿不是人人都有，但也不是公司一句“没有”就真的没有。",
    oneLiner: "先分清是你主动走、公司辞退还是协商解除，再谈赔偿。",
    targetUsers: ["准备离职的人", "突然被通知离职的人"],
    targetStages: ["intern", "graduate"],
    difficulty: "watchout",
    estimatedMinutes: 8,
    emergencyLevel: 1,
    isFeatured: false,
    starterPriority: 74,
    popularityScore: 78,
    coverStyle: "amber",
    aliases: ["离职赔偿是什么"],
    keywords: ["离职赔偿", "辞退", "补偿", "协商解除"],
    tags: ["维权", "劳动关系"],
    preparationItems: ["劳动合同", "工资流水或工资条", "解除通知或聊天记录"],
    steps: [
      { title: "先判断离职类型", body: "主动辞职、公司辞退、协商解除，处理方式和补偿逻辑不一样。", tip: "一上来先分类型。" },
      { title: "整理劳动关系证据", body: "合同、工资流水、工牌、考勤、聊天记录都可能用得上。", tip: "不是只有纸质合同才算证据。" },
      { title: "不要口头答应模糊方案", body: "涉及赔偿、交接、离职时间时，尽量要书面。", tip: "口头说“后面补给你”风险很大。" },
      { title: "必要时咨询劳动维权渠道", body: "如果你感觉明显不对劲，就去找更专业的渠道问，不要全靠猜。", tip: "越早问，越不容易错过时间点。" },
    ],
    commonPitfalls: ["没分清离职类型就谈赔偿", "只口头沟通不留文字", "证据到最后才开始补"],
    keyQuestions: ["这次离职属于哪种情况", "公司给的方案有没有写清楚", "我手里能证明劳动关系的材料有哪些"],
    relatedScenarioSlugs: ["what-is-probation", "salary-structure"],
  },
];
const scenarioInputsPart4: ScenarioSeedInput[] = [
  {
    slug: "graduate-subsidy",
    title: "应届生补贴",
    categorySlug: "jobs",
    summary: "应届生补贴不是全国一个版本，不同城市、学历、落户状态和社保条件差异很大。",
    oneLiner: "先查你所在城市的官方条件，再看自己是不是满足时间、学历和社保要求。",
    targetUsers: ["刚毕业准备就业的人", "准备去外地工作的毕业生"],
    targetStages: ["graduate", "new-city"],
    difficulty: "standard",
    estimatedMinutes: 6,
    emergencyLevel: 0,
    isFeatured: false,
    starterPriority: 63,
    popularityScore: 70,
    coverStyle: "violet",
    aliases: ["毕业生补贴"],
    keywords: ["应届生补贴", "人才补贴", "毕业补贴"],
    tags: ["毕业", "政策"],
    preparationItems: ["毕业证或学籍信息", "劳动合同或社保信息", "所在城市官方政策入口"],
    steps: [
      { title: "先找官方政策入口", body: "优先看当地人社、人才服务或政务平台，不要只看二手总结。", tip: "政策更新很快，别只信旧帖子。" },
      { title: "核对自己是否符合条件", body: "学历、户籍、社保缴纳时间、首次就业等条件都可能影响结果。", tip: "看完条件再准备材料，不然容易白忙。" },
      { title: "准备申请材料", body: "一般会用到身份证、毕业信息、劳动合同、社保记录、银行卡等。", tip: "先把电子版整理好。" },
      { title: "按时间节点提交", body: "很多补贴有申请窗口期，过了时间可能就没了。", tip: "把截止时间设提醒。" },
    ],
    commonPitfalls: ["只看别人经验不看本地官方要求", "没注意社保和时间门槛", "材料不全导致反复补交"],
    keyQuestions: ["我所在城市有什么补贴", "我是否符合申请条件", "申请截止时间是什么时候"],
    relatedScenarioSlugs: ["salary-structure", "new-city-first-24-hours"],
  },
  {
    slug: "national-or-provincial-exam",
    title: "国考省考是什么",
    categorySlug: "jobs",
    summary: "国考和省考都是公务员考试，但招录单位、时间安排和岗位分布不一样，别先被名词吓住。",
    oneLiner: "先知道自己是在了解方向，不是明天就得报名，先把概念分清楚。",
    targetUsers: ["想了解体制内考试的人", "大三大四开始规划毕业方向的人"],
    targetStages: ["graduate"],
    difficulty: "standard",
    estimatedMinutes: 6,
    emergencyLevel: 0,
    isFeatured: false,
    starterPriority: 58,
    popularityScore: 64,
    coverStyle: "violet",
    aliases: ["国考省考区别"],
    keywords: ["国考", "省考", "公务员", "考试"],
    tags: ["毕业方向"],
    preparationItems: ["毕业时间规划", "大致职业偏好", "官方招录公告入口"],
    steps: [
      { title: "先知道它们都是招录考试", body: "国考偏中央及其直属单位，省考偏地方岗位。", tip: "不用先背定义，先知道大方向就够。" },
      { title: "看时间线和岗位来源", body: "招录公告、报名、笔试、面试通常都有固定节奏。", tip: "公告时间一定要看当年官方发布。" },
      { title: "再看自己适不适合", body: "别只看“稳定”，还要看城市、岗位内容、限制条件和准备周期。", tip: "先了解，再决定要不要投入备考。" },
      { title: "别被碎片信息牵着跑", body: "网上经验可以参考，但最终还是回到公告和岗位表。", tip: "岗位条件是最硬的信息。" },
    ],
    commonPitfalls: ["一上来就刷经验帖不看公告", "把国考省考当成同一件事", "没想清楚岗位和城市就盲目备考"],
    keyQuestions: ["国考和省考主要区别是什么", "岗位条件怎么看", "我现在是了解还是准备备考"],
    relatedScenarioSlugs: ["graduate-subsidy", "what-is-referral"],
  },
  {
    slug: "what-is-referral",
    title: "什么是内推",
    categorySlug: "jobs",
    summary: "内推不是“走后门”，更像是有人把你的简历送到更容易被看见的位置。",
    oneLiner: "你可以把它理解成推荐通道，但最终能不能过，还是看岗位匹配和面试表现。",
    targetUsers: ["准备投简历的学生和毕业生"],
    targetStages: ["intern", "graduate"],
    difficulty: "easy",
    estimatedMinutes: 5,
    emergencyLevel: 0,
    isFeatured: false,
    starterPriority: 61,
    popularityScore: 75,
    coverStyle: "mint",
    aliases: ["内推是什么意思"],
    keywords: ["内推", "简历", "求职"],
    tags: ["求职"],
    preparationItems: ["更新过的简历", "目标岗位 JD", "简短的自我介绍"],
    steps: [
      { title: "先准备好能发出去的简历", body: "内推最怕别人愿意帮你时，你自己材料还没准备好。", tip: "简历先做成可随时投递的版本。" },
      { title: "找对人、说清岗位", body: "告诉对方你想投什么岗位、地点和最匹配的经历。", tip: "别只发一句“能帮我内推吗”。" },
      { title: "礼貌跟进但别频繁催", body: "给对方留处理时间，跟进时说清岗位名称和投递状态。", tip: "内推不是马上就会有面试。" },
      { title: "拿到机会后还是靠自己", body: "简历过筛、笔试、面试这些环节还是要自己过。", tip: "把内推当加速，不要当保送。" },
    ],
    commonPitfalls: ["简历没准备好就到处求内推", "开口方式太空泛", "把内推当成一定成功"],
    keyQuestions: ["我投的岗位是什么", "我最匹配的经历有哪些", "怎么礼貌地发起请求"],
    relatedScenarioSlugs: ["interview-self-introduction", "what-is-tripartite-agreement"],
  },
  {
    slug: "interview-self-introduction",
    title: "面试自我介绍",
    categorySlug: "jobs",
    summary: "自我介绍不是背一段漂亮话，而是让面试官快速知道你是谁、做过什么、为什么适合这个岗位。",
    oneLiner: "先讲身份，再讲经历，再讲和岗位的连接，控制在一分半左右最好。",
    targetUsers: ["第一次实习或求职面试的人"],
    targetStages: ["intern", "graduate"],
    difficulty: "standard",
    estimatedMinutes: 6,
    emergencyLevel: 0,
    isFeatured: true,
    starterPriority: 81,
    popularityScore: 89,
    coverStyle: "mint",
    aliases: ["面试开场怎么说"],
    keywords: ["面试", "自我介绍", "校招", "实习"],
    tags: ["求职", "表达"],
    preparationItems: ["目标岗位 JD", "自己的简历", "1-2 个最能打的经历"],
    steps: [
      { title: "先讲你现在是谁", body: "学校/专业/当前阶段一句带过，不要讲太长。", tip: "开头先让对方定位你。" },
      { title: "再讲最相关的经历", body: "挑 1-2 段和岗位最有关的经历，说清你做了什么和结果。", tip: "经历比性格词更有说服力。" },
      { title: "最后连回这个岗位", body: "说明你为什么想投，以及你觉得自己能带来什么。", tip: "别泛泛说“想锻炼自己”。" },
      { title: "控制时长并多练几遍", body: "1-1.5 分钟通常比较稳，太短没信息，太长容易散。", tip: "录音一遍就知道哪里啰嗦。" },
    ],
    commonPitfalls: ["介绍太长像背作文", "只讲性格不讲经历", "讲了很多却没连回岗位"],
    keyQuestions: ["我最该讲哪两段经历", "岗位最看重什么", "这一分钟里我想让对方记住什么"],
    scripts: [
      {
        title: "一分半自我介绍模板",
        scriptType: "opening",
        content: "你好，我叫 ____，目前是 ____。我最近和这个岗位最相关的经历主要有两段：第一段是 ____，我主要负责 ____，结果是 ____；第二段是 ____，这让我更熟悉 ____。我这次投这个岗位，是因为我希望把这些经验继续用在 ____ 上，也很想在更真实的业务里继续提升。",
      },
    ],
    relatedScenarioSlugs: ["what-is-referral", "salary-structure"],
  },
  {
    slug: "take-train",
    title: "如何坐火车",
    categorySlug: "transport",
    summary: "第一次坐火车，不是怕不会坐，而是怕流程一乱就赶不上车。",
    oneLiner: "提前确认车次、车站、检票口和身份证件，按时间往前推就不慌。",
    targetUsers: ["第一次自己出远门的人"],
    targetStages: ["freshman", "new-city", "graduate"],
    difficulty: "easy",
    estimatedMinutes: 5,
    emergencyLevel: 0,
    isFeatured: true,
    starterPriority: 77,
    popularityScore: 84,
    coverStyle: "sky",
    aliases: ["坐火车流程"],
    keywords: ["火车", "车站", "检票", "候车"],
    tags: ["出行"],
    preparationItems: ["身份证", "车票信息", "出发车站和到达时间"],
    steps: [
      { title: "提前确认不是哪个站都一样", body: "同一个城市可能有多个火车站，先看清出发站。", tip: "别只看城市名。" },
      { title: "预留进站时间", body: "安检、找候车室、找检票口都需要时间。", tip: "第一次宁早勿晚。" },
      { title: "检票后看车厢和座位", body: "上车前先看车厢号，再看座位号。", tip: "别跟着人群乱挤。" },
      { title: "到站前提前收拾", body: "快到站时就把随身物品清点一遍。", tip: "手机、证件、耳机最容易忘。" },
    ],
    commonPitfalls: ["跑错火车站", "时间卡太紧导致慌乱", "下车前漏拿随身物品"],
    keyQuestions: ["我从哪个站出发", "提前多久到站更稳", "我的车厢和座位在哪里"],
    relatedScenarioSlugs: ["take-high-speed-rail", "take-subway"],
  },
  {
    slug: "take-high-speed-rail",
    title: "如何坐高铁",
    categorySlug: "transport",
    summary: "高铁流程和火车很像，但节奏更快，最怕进站慢、走错口、到站下错站。",
    oneLiner: "先确认车次和站，再按屏幕信息走，不要只听别人说。",
    targetUsers: ["第一次坐高铁的人"],
    targetStages: ["freshman", "new-city", "graduate"],
    difficulty: "easy",
    estimatedMinutes: 5,
    emergencyLevel: 0,
    isFeatured: true,
    starterPriority: 76,
    popularityScore: 86,
    coverStyle: "sky",
    aliases: ["坐高铁流程"],
    keywords: ["高铁", "检票", "站台"],
    tags: ["出行"],
    preparationItems: ["身份证", "车次信息", "出发站和到达站"],
    steps: [
      { title: "先认准出发站和车次", body: "高铁站名和城市名不总是一回事，别看错。", tip: "像“南站”“东站”一定要核对。" },
      { title: "看大屏找候车区", body: "以站内屏幕和官方信息为准，不确定就问工作人员。", tip: "不要一直低头只看手机。" },
      { title: "检票后按车厢方向走", body: "站台上通常会有车厢区段提示，先看自己在哪一节。", tip: "别等车来了再找。" },
      { title: "下车时确认是不是自己的站", body: "快到站前看屏幕和广播，不要跟着别人盲目下。", tip: "尤其路线中间有多个相似站名时。" },
    ],
    commonPitfalls: ["站名看错", "候车信息没刷新", "下车站判断失误"],
    keyQuestions: ["出发站和到达站是否确认过", "候车区在哪里", "我该在哪个区段等车"],
    relatedScenarioSlugs: ["take-train", "take-airplane"],
  },
  {
    slug: "take-airplane",
    title: "如何坐飞机",
    categorySlug: "transport",
    summary: "第一次坐飞机，最容易被值机、托运、安检液体规则这些流程卡住。",
    oneLiner: "先确认航站楼和值机时间，再搞清楚行李规则。",
    targetUsers: ["第一次坐飞机的人"],
    targetStages: ["freshman", "new-city", "graduate"],
    difficulty: "standard",
    estimatedMinutes: 7,
    emergencyLevel: 0,
    isFeatured: false,
    starterPriority: 69,
    popularityScore: 78,
    coverStyle: "ocean",
    aliases: ["坐飞机流程"],
    keywords: ["飞机", "值机", "托运", "安检"],
    tags: ["出行"],
    preparationItems: ["身份证件", "航班信息", "行李尺寸和重量"],
    steps: [
      { title: "先看航站楼和起飞时间", body: "机场通常分多个航站楼，跑错地方会很麻烦。", tip: "提早到机场是第一次坐飞机最稳的做法。" },
      { title: "确认是否需要值机和托运", body: "有行李就先看是否超重、是否要托运。", tip: "液体、充电宝这些规则提前看。" },
      { title: "过安检和找登机口", body: "证件、登机牌和电子设备提前准备好。", tip: "安检前把口袋清一清会快很多。" },
      { title: "登机后看座位和行李", body: "登机后先放好行李，再对号入座。", tip: "别把重要证件放进行李架后够不到。" },
    ],
    commonPitfalls: ["跑错航站楼", "行李规则没看", "安检前准备不足导致手忙脚乱"],
    keyQuestions: ["我在哪个航站楼", "行李能不能直接带上飞机", "什么时候开始登机"],
    relatedScenarioSlugs: ["take-high-speed-rail", "call-ride-hailing"],
  },
  {
    slug: "take-subway",
    title: "如何坐地铁",
    categorySlug: "transport",
    summary: "坐地铁最容易慌的不是刷卡，而是方向、出口和换乘路线。",
    oneLiner: "先确认方向和终点站，再进站，不要进去了才开始猜。",
    targetUsers: ["第一次到大城市坐地铁的人"],
    targetStages: ["freshman", "new-city", "intern"],
    difficulty: "easy",
    estimatedMinutes: 4,
    emergencyLevel: 0,
    isFeatured: false,
    starterPriority: 75,
    popularityScore: 83,
    coverStyle: "ocean",
    aliases: ["地铁怎么坐"],
    keywords: ["地铁", "方向", "换乘", "出口"],
    tags: ["城市出行"],
    preparationItems: ["目的地站名", "手机支付或交通卡"],
    steps: [
      { title: "先查终点站方向", body: "地铁最容易错的不是线路，而是方向。", tip: "终点站名字就是方向提示。" },
      { title: "进站后再确认换乘", body: "看清换乘站和出口编号，别只看线路颜色。", tip: "换乘多的时候更要提前看。" },
      { title: "出站时认准出口", body: "同一站不同出口可能差很远。", tip: "看地图时顺手记出口编号。" },
      { title: "不确定就问站务员", body: "比你在站内原地兜圈子更有效。", tip: "新城市里会问路不是丢脸，是节省时间。" },
    ],
    commonPitfalls: ["方向坐反", "换乘出口没提前看", "出站口选错绕远路"],
    keyQuestions: ["我要坐哪个方向", "需不需要换乘", "从哪个出口出来最近"],
    relatedScenarioSlugs: ["take-bus", "call-ride-hailing", "new-city-survival-guide"],
  },
  {
    slug: "take-bus",
    title: "如何坐公交",
    categorySlug: "transport",
    summary: "公交看着简单，但第一次最容易卡在上下车站点、付款方式和反方向。",
    oneLiner: "先看站名和行驶方向，再看是否需要扫码或投币。",
    targetUsers: ["第一次在陌生城市坐公交的人"],
    targetStages: ["freshman", "new-city", "independent"],
    difficulty: "easy",
    estimatedMinutes: 4,
    emergencyLevel: 0,
    isFeatured: false,
    starterPriority: 71,
    popularityScore: 77,
    coverStyle: "sky",
    aliases: ["公交怎么坐"],
    keywords: ["公交", "站点", "扫码", "方向"],
    tags: ["城市出行"],
    preparationItems: ["目标站名", "手机支付或零钱"],
    steps: [
      { title: "先确认是不是反方向", body: "同一路公交，马路两边方向可能完全相反。", tip: "先看终点站。" },
      { title: "上车前确认付款方式", body: "有的扫码、有的刷卡、有的还支持投币。", tip: "别上车了才翻手机。" },
      { title: "注意提前准备下车", body: "到站前提前站到门附近，别等车停了再往前挤。", tip: "看地图时留意快到站的提示。" },
      { title: "下车后再核对方向", body: "下车后看一眼自己是不是在正确一侧。", tip: "陌生地方别急着走反方向。" },
    ],
    commonPitfalls: ["坐反方向", "上车才发现没法付款", "到站了还来不及下车"],
    keyQuestions: ["这辆车往哪边开", "怎么付款", "我还有几站下车"],
    relatedScenarioSlugs: ["take-subway", "new-city-first-24-hours"],
  },
  {
    slug: "call-ride-hailing",
    title: "如何叫网约车",
    categorySlug: "transport",
    summary: "叫网约车最怕的是定位不准、上错车、平台信息和车牌没核对。",
    oneLiner: "先设好上车点，核对车牌和司机信息，再上车。",
    targetUsers: ["第一次一个人打车的人"],
    targetStages: ["freshman", "new-city", "intern"],
    difficulty: "easy",
    estimatedMinutes: 4,
    emergencyLevel: 1,
    isFeatured: true,
    starterPriority: 73,
    popularityScore: 81,
    coverStyle: "ocean",
    aliases: ["怎么叫网约车"],
    keywords: ["网约车", "打车", "车牌", "定位"],
    tags: ["城市出行", "安全"],
    preparationItems: ["手机定位", "目的地", "可支付方式"],
    steps: [
      { title: "先把定位点选准", body: "上车点越明确，司机越容易找到你。", tip: "商场、地铁站这类地方最好加备注。" },
      { title: "看清车型和价格", body: "不同车型价格差很多，别手滑选错。", tip: "赶时间也先看一眼。" },
      { title: "上车前核对车牌和司机", body: "别因为司机喊你名字就上车。", tip: "至少核对车牌尾号和车型。" },
      { title: "不舒服就及时改计划", body: "如果路线不对或你感觉不安全，及时联系平台或结束行程。", tip: "安全永远优先于不好意思。" },
    ],
    commonPitfalls: ["定位点选得太模糊", "没核对车牌就上车", "路线明显不对也不敢开口"],
    keyQuestions: ["我的上车点准不准", "车牌和平台信息对不对", "司机路线是否正常"],
    relatedScenarioSlugs: ["take-subway", "new-city-survival-guide"],
  },
  {
    slug: "new-city-survival-guide",
    title: "陌生城市生存指南",
    categorySlug: "city-survival",
    summary: "第一次到陌生城市，不是所有事都要一次搞定，但有几件事越早确认越安心。",
    oneLiner: "先把住、行、医、警、支付这五条线摸清，日子就稳很多。",
    targetUsers: ["去外地读书、实习或工作的人"],
    targetStages: ["freshman", "intern", "graduate", "new-city"],
    difficulty: "standard",
    estimatedMinutes: 10,
    emergencyLevel: 1,
    isFeatured: true,
    starterPriority: 94,
    popularityScore: 92,
    coverStyle: "ocean",
    aliases: ["陌生城市怎么活"],
    keywords: ["陌生城市", "生活指南", "落地"],
    tags: ["新城市", "总览"],
    preparationItems: ["落脚点地址", "常用支付方式", "家人/朋友紧急联系人", "重要证件电子备份"],
    steps: [
      { title: "先把住和行确定下来", body: "住在哪里、通勤怎么走、晚上怎么回去，这三件事先搞清。", tip: "第一晚的安全感最重要。" },
      { title: "再把医疗和求助入口记住", body: "附近医院、药店、派出所、地铁站、打车点都先看一遍。", tip: "不是出事了才开始找。" },
      { title: "确认日常支付和通信", body: "手机号、银行卡、交通支付、网络这些是整个生活系统的底层。", tip: "任何一个卡住都容易连锁慌张。" },
      { title: "给自己留一个缓冲日", body: "新城市前两天少排太满，让自己有时间熟悉周边。", tip: "别要求自己一上来就像本地人。" },
    ],
    commonPitfalls: ["一下车就同时处理太多事情", "附近基础设施完全没摸清", "没有给自己留缓冲时间"],
    keyQuestions: ["我住的地方周边有哪些关键设施", "我最常走的路线是什么", "遇到突发情况先找谁"],
    relatedScenarioSlugs: ["new-city-first-24-hours", "take-subway", "go-to-hospital", "call-police"],
  },
  {
    slug: "first-independent-living-guide",
    title: "第一次独自生活指南",
    categorySlug: "campus-transition",
    summary: "独自生活的难，不是某一件大事，而是一堆看起来很小的事情第一次都要自己做。",
    oneLiner: "先把吃、穿、洗、住、钱这五件基础小事做顺，心里就没那么慌。",
    targetUsers: ["刚离开家的大学生", "第一次独居的人"],
    targetStages: ["freshman", "independent"],
    difficulty: "easy",
    estimatedMinutes: 8,
    emergencyLevel: 0,
    isFeatured: true,
    starterPriority: 93,
    popularityScore: 90,
    coverStyle: "violet",
    aliases: ["第一次一个人生活"],
    keywords: ["独自生活", "独居", "大一"],
    tags: ["新手保护", "校园过渡"],
    preparationItems: ["基础生活预算", "常用日用品清单", "紧急联系人"],
    steps: [
      { title: "先把最基础的生活循环跑起来", body: "吃饭、洗衣、洗漱、作息、垃圾这些先建立自己的节奏。", tip: "小事稳定，心就稳定。" },
      { title: "把钱和证件放在固定位置", body: "银行卡、身份证、钥匙、门禁卡固定放，能少掉很多无谓焦虑。", tip: "别每天临出门都找一遍。" },
      { title: "学会主动问", body: "不会就问室友、同学、物业、客服，比自己硬扛高效很多。", tip: "第一次不会很正常。" },
      { title: "给自己留最小应急包", body: "常用药、纸巾、充电线、备用现金这类东西，关键时刻很顶用。", tip: "不需要多豪华，能应急就够。" },
    ],
    commonPitfalls: ["把所有不会的事都憋着不问", "生活物品没有固定位置", "小事拖太久最后一起爆发"],
    keyQuestions: ["我每天最常重复的生活动作有哪些", "哪些东西需要固定收纳", "遇到不会的事先问谁"],
    relatedScenarioSlugs: ["wash-clothes", "wash-underwear", "how-to-get-phone-card"],
  },
  {
    slug: "new-city-first-24-hours",
    title: "新城市落地 24 小时要做什么",
    categorySlug: "city-survival",
    summary: "刚到一个新城市的前 24 小时，不要追求什么都搞定，先把最影响安全感和行动力的事情排出来。",
    oneLiner: "先住下、先吃上、先连上网、先认路，再处理别的。",
    targetUsers: ["刚到新城市读书、实习或工作的人"],
    targetStages: ["freshman", "intern", "graduate", "new-city"],
    difficulty: "easy",
    estimatedMinutes: 6,
    emergencyLevel: 1,
    isFeatured: true,
    starterPriority: 91,
    popularityScore: 87,
    coverStyle: "ocean",
    aliases: ["落地新城市第一天"],
    keywords: ["新城市", "24小时", "落地"],
    tags: ["行动清单"],
    preparationItems: ["住处地址", "手机电量和充电器", "紧急联系人", "少量现金"],
    steps: [
      { title: "先把落脚点安顿好", body: "确认门锁、洗手间、热水、充电和网络。", tip: "第一晚先睡得下最重要。" },
      { title: "再把吃饭和出行摸清", body: "附近便利店、地铁站、公交站、打车点先知道。", tip: "不要饿着肚子处理所有事。" },
      { title: "处理必须当天办的事", body: "报到、入住、身份证件登记、联系房东或公司这类优先。", tip: "能明天办的事别全挤今天。" },
      { title: "睡前做一次明天计划", body: "把第二天要去的地方、路线和要带的东西写下来。", tip: "这样第二天起床会轻松很多。" },
    ],
    commonPitfalls: ["第一天安排太满", "住处基础条件没确认就出门", "没有提前规划第二天路线"],
    keyQuestions: ["今晚先确保哪几件事", "周边最关键的设施在哪里", "明天出门要带哪些东西"],
    relatedScenarioSlugs: ["new-city-survival-guide", "call-ride-hailing", "take-subway"],
  },
];

const scenarioInputs: ScenarioSeedInput[] = [
  ...scenarioInputsPart1,
  ...scenarioInputsPart2,
  ...scenarioInputsPart3,
  ...scenarioInputsPart4,
];

export const scenarios: ScenarioDetail[] = scenarioInputs.map(createScenario);

export const learningPaths: LearningPath[] = [
  {
    id: "freshman-survival",
    title: "大一生存路线",
    slug: "freshman-survival",
    description: "从手机卡、银行卡到洗衣和看病，先把离家后的基础动作跑顺。",
    cover: "violet",
    sortOrder: 1,
    targetStages: ["freshman"],
    scenarioSlugs: [
      "how-to-get-phone-card",
      "how-to-get-bank-card",
      "wash-clothes",
      "wash-underwear",
      "go-to-hospital",
      "take-train",
    ],
  },
  {
    id: "independent-living",
    title: "大学生独立生活路线",
    slug: "independent-living",
    description: "把租房、水电、快递、日常缴费这些独立生活刚需先踩熟。",
    cover: "sand",
    sortOrder: 2,
    targetStages: ["independent"],
    scenarioSlugs: [
      "first-independent-living-guide",
      "check-utilities",
      "send-courier",
      "how-to-rent-house",
      "pay-rent-utilities",
      "install-broadband",
    ],
  },
  {
    id: "first-internship",
    title: "第一次实习路线",
    slug: "first-internship",
    description: "从内推和面试，到工资结构、试用期和五险一金，先把职场第一步走稳。",
    cover: "mint",
    sortOrder: 3,
    targetStages: ["intern"],
    scenarioSlugs: [
      "what-is-referral",
      "interview-self-introduction",
      "salary-structure",
      "read-first-pay-slip",
      "what-is-probation",
      "what-is-insurance-housing-fund",
    ],
  },
  {
    id: "graduate-job-hunt",
    title: "毕业找工作路线",
    slug: "graduate-job-hunt",
    description: "应届生最容易卡住的三方、补贴、岗位选择和离职边界，集中搞懂。",
    cover: "violet",
    sortOrder: 4,
    targetStages: ["graduate"],
    scenarioSlugs: [
      "what-is-tripartite-agreement",
      "graduate-subsidy",
      "national-or-provincial-exam",
      "salary-structure",
      "resignation-compensation",
      "what-is-insurance-housing-fund",
    ],
  },
  {
    id: "new-city-survival",
    title: "陌生城市生存路线",
    slug: "new-city-survival",
    description: "第一天落地、日常出行、看病、求助和租房，全都按新城市视角串起来。",
    cover: "ocean",
    sortOrder: 5,
    targetStages: ["new-city"],
    scenarioSlugs: [
      "new-city-first-24-hours",
      "new-city-survival-guide",
      "take-subway",
      "call-ride-hailing",
      "go-to-hospital",
      "how-to-rent-house",
    ],
  },
];

export const toolkitResources: ToolkitResource[] = [
  {
    id: "rent-checklist",
    title: "租房检查清单",
    slug: "rent-checklist",
    summary: "看房和签约前后都能直接照着核对。",
    categorySlug: "housing",
    relatedScenarioSlug: "how-to-rent-house",
    downloadName: "租房检查清单.txt",
    copyText: "租房检查清单\n1. 预算和通勤上限先算清\n2. 采光、隔音、潮湿、水压都检查\n3. 水电物业网费问清\n4. 押金、中介费、维修责任写清\n5. 入住前拍照留证",
    items: [
      { id: "rent-1", content: "预算、通勤、付款时间先算清" },
      { id: "rent-2", content: "墙面、地板、家具家电现状拍照" },
      { id: "rent-3", content: "确认水电物业网费的收费方式" },
      { id: "rent-4", content: "问清押金退回时间和违约条款" },
      { id: "rent-5", content: "入住当天把问题点发聊天留证" },
    ],
  },
  {
    id: "hospital-checklist",
    title: "看病准备清单",
    slug: "hospital-checklist",
    summary: "第一次去医院前先带齐这些，能少跑很多路。",
    categorySlug: "medical-emergency",
    relatedScenarioSlug: "go-to-hospital",
    downloadName: "看病准备清单.txt",
    copyText: "看病准备清单\n- 身份证或医保码\n- 既往病历/药单\n- 症状开始时间\n- 过敏史和用药史\n- 手机支付方式",
    items: [
      { id: "hospital-1", content: "身份证、医保码、手机电量充足" },
      { id: "hospital-2", content: "把症状开始时间记下来" },
      { id: "hospital-3", content: "有过敏史或正在吃药要提前想好怎么说" },
      { id: "hospital-4", content: "检查结果和单据不要随手丢" },
    ],
  },
  {
    id: "courier-complaint-template",
    title: "快递丢失维权模板",
    slug: "courier-complaint-template",
    summary: "一段话说明订单、物流和诉求，不容易被客服带偏。",
    categorySlug: "rights",
    relatedScenarioSlug: "courier-lost-claim",
    downloadName: "快递维权模板.txt",
    copyText: "你好，这个订单已经超过正常时效/显示签收但我未收到。我已整理订单截图、物流轨迹和商品金额，请帮我登记丢件并告知理赔流程、赔偿标准和回复时限。",
    items: [
      { id: "courier-1", content: "订单号和物流截图先整理好" },
      { id: "courier-2", content: "说明是丢件、少件还是误签" },
      { id: "courier-3", content: "明确表达要流程、标准和时限" },
    ],
  },
  {
    id: "interview-template",
    title: "面试自我介绍模板",
    slug: "interview-template",
    summary: "把一分半自我介绍压缩成好记的骨架。",
    categorySlug: "jobs",
    relatedScenarioSlug: "interview-self-introduction",
    downloadName: "面试自我介绍模板.txt",
    copyText: "你好，我叫____，目前是____。和这个岗位最相关的经历有两段：第一段是____，我主要负责____，结果是____；第二段是____。我投这个岗位，是因为我想把这些经验继续用在____上。",
    items: [
      { id: "intro-1", content: "身份一句话" },
      { id: "intro-2", content: "最相关经历 1" },
      { id: "intro-3", content: "最相关经历 2" },
      { id: "intro-4", content: "为什么投这个岗位" },
    ],
  },
  {
    id: "leave-request-template",
    title: "请假沟通模板",
    slug: "leave-request-template",
    summary: "把原因、时间、交接说清楚，比长篇解释更有效。",
    categorySlug: "jobs",
    downloadName: "请假沟通模板.txt",
    copyText: "你好，我因为____，需要在____请假/调休，预计影响的工作是____，我已经先安排了____，如果需要补充交接我可以马上处理。",
    items: [
      { id: "leave-1", content: "先说请假时间" },
      { id: "leave-2", content: "简洁说明原因" },
      { id: "leave-3", content: "说明交接安排" },
    ],
  },
  {
    id: "job-trap-checklist",
    title: "求职避坑清单",
    slug: "job-trap-checklist",
    summary: "看到这些信号时，别急着觉得自己挑剔。",
    categorySlug: "jobs",
    downloadName: "求职避坑清单.txt",
    copyText: "求职避坑清单\n- 岗位职责和薪资口径模糊\n- 试用期规则说不清\n- 面试就催签且不给文字材料\n- 长时间不发 offer 只口头承诺\n- 要你交押金或培训费",
    items: [
      { id: "jobtrap-1", content: "岗位职责是否清楚" },
      { id: "jobtrap-2", content: "薪资结构是否透明" },
      { id: "jobtrap-3", content: "试用期和加班规则是否清楚" },
      { id: "jobtrap-4", content: "有没有不合理收费" },
    ],
  },
  {
    id: "labor-contract-checks",
    title: "劳动合同重点检查项",
    slug: "labor-contract-checks",
    summary: "合同里最该逐条确认的不是废话，而是这些真正影响你的条款。",
    categorySlug: "rights",
    downloadName: "劳动合同检查项.txt",
    copyText: "劳动合同重点检查项\n1. 岗位和工作地点\n2. 薪资结构和发薪日\n3. 试用期与转正规则\n4. 社保公积金\n5. 加班与休假\n6. 离职和违约约定",
    items: [
      { id: "contract-1", content: "岗位和地点是否一致" },
      { id: "contract-2", content: "薪资和发薪日是否写明" },
      { id: "contract-3", content: "试用期和转正标准是否明确" },
      { id: "contract-4", content: "离职条款是否能看懂" },
    ],
  },
  {
    id: "salary-template",
    title: "工资结构看懂模板",
    slug: "salary-template",
    summary: "把 offer 和工资条对起来看，马上知道自己到手为什么不是那个数。",
    categorySlug: "finance",
    relatedScenarioSlug: "salary-structure",
    downloadName: "工资结构模板.txt",
    copyText: "工资结构模板\n固定：基本工资\n浮动：绩效/奖金/提成\n扣款：五险一金/个税/考勤\n结论：稳定到手 = 固定 + 大概率能拿到的浮动 - 固定扣款",
    items: [
      { id: "salary-1", content: "先列固定收入" },
      { id: "salary-2", content: "再列浮动部分" },
      { id: "salary-3", content: "最后写固定扣款" },
    ],
  },
  {
    id: "insurance-fastcard",
    title: "社保公积金速查卡",
    slug: "insurance-fastcard",
    summary: "不求背会，先知道每一项大概是干什么的。",
    categorySlug: "jobs",
    relatedScenarioSlug: "what-is-insurance-housing-fund",
    downloadName: "社保公积金速查卡.txt",
    copyText: "五险一金速查\n养老：长期积累\n医疗：看病报销\n失业：失业保障\n工伤：工伤事故保障\n生育：生育相关保障\n公积金：住房相关",
    items: [
      { id: "insurance-1", content: "养老：长期保障" },
      { id: "insurance-2", content: "医疗：就医报销" },
      { id: "insurance-3", content: "公积金：住房相关" },
    ],
  },
  {
    id: "new-city-checklist",
    title: "陌生城市落地 24 小时 checklist",
    slug: "new-city-checklist",
    summary: "第一天先稳住这几件事，别被“什么都要处理”压垮。",
    categorySlug: "city-survival",
    relatedScenarioSlug: "new-city-first-24-hours",
    downloadName: "新城市落地清单.txt",
    copyText: "新城市 24 小时清单\n- 住处先安顿\n- 吃饭和买水先解决\n- 手机和充电先稳定\n- 认路、认站、认医院和派出所\n- 睡前排明天路线",
    items: [
      { id: "city-1", content: "住处热水、门锁、充电先确认" },
      { id: "city-2", content: "附近便利店、地铁站先摸清" },
      { id: "city-3", content: "紧急联系人和明天路线先写下" },
    ],
  },
  {
    id: "landlord-chat-template",
    title: "和房东沟通模板",
    slug: "landlord-chat-template",
    summary: "把价格、押金、水电和维修责任一次问清，比来回追着问省心。",
    categorySlug: "housing",
    relatedScenarioSlug: "how-to-rent-house",
    downloadName: "房东沟通模板.txt",
    copyText: "你好，我第一次租房，想先确认几件事：房租包含哪些费用？押金怎么退？水电按什么标准算？家具家电坏了谁负责修？如果这些都清楚，我再继续安排看房和签约。",
    items: [
      { id: "landlord-1", content: "房租包含哪些费用" },
      { id: "landlord-2", content: "押金怎么退" },
      { id: "landlord-3", content: "水电按什么标准算" },
      { id: "landlord-4", content: "维修责任归谁" },
    ],
  },
];

export const simulatorScenarios: SimulatorScenario[] = [
  {
    id: "bank-simulator",
    slug: "bank-simulator",
    title: "去银行办卡怎么说",
    summary: "练一遍储蓄卡办理时最常见的开场、追问和确认方式。",
    relatedScenarioSlug: "how-to-get-bank-card",
    goals: [
      { id: "open-card", label: "开储蓄卡", openingLine: "你好，我想办一张储蓄卡，第一次办，想先确认一下需要哪些材料。", successLine: "材料、费用和限额都问清之后再继续办理。" },
      { id: "ask-fee", label: "问手续费", openingLine: "你好，我想先了解一下这张卡有没有年费、短信通知费或其他费用。", successLine: "把费用问清，比办完再后悔强很多。" },
      { id: "ask-limit", label: "问限额", openingLine: "你好，我想确认一下这张卡线上转账和取现的限额大概是多少。", successLine: "先看限额，才知道这张卡是不是适合你。" },
    ],
    nodes: [
      {
        id: "start",
        speaker: "other",
        title: "柜员开口",
        message: "柜员：你好，需要办什么业务？",
        options: [
          { id: "bank-a", label: "直接说想办储蓄卡，并说明自己是第一次办", nextNodeId: "ask-materials", feedback: "这句很稳，既明确了需求，也给对方释放了“请按步骤说”的信号。", tone: "good", appendToScript: "你好，我想办一张储蓄卡，第一次办，想先确认一下流程和需要的材料。" },
          { id: "bank-b", label: "就说“你们哪个卡最好”", nextNodeId: "ask-materials", feedback: "这句太泛，对方容易直接把你带进推销节奏。", tone: "risky", appendToScript: "你们这边哪个卡最好？" },
        ],
      },
      {
        id: "ask-materials",
        speaker: "other",
        title: "柜员说明材料",
        message: "柜员：身份证和手机号一般都要，具体你还有什么想确认的吗？",
        options: [
          { id: "bank-c", label: "继续问费用和短信通知费", nextNodeId: "ask-limit", feedback: "对，这一步最该追问费用。", tone: "good", appendToScript: "我还想确认一下，这张卡有没有年费、短信通知费或者其他固定收费？" },
          { id: "bank-d", label: "什么都不问，直接说办吧", nextNodeId: "finish", feedback: "太快了，后面最容易在收费和限额上踩坑。", tone: "risky", appendToScript: "那就直接办吧。" },
        ],
      },
      {
        id: "ask-limit",
        speaker: "other",
        title: "柜员继续回应",
        message: "柜员：费用你可以再看一下，有些业务默认开通。还有别的问题吗？",
        options: [
          { id: "bank-e", label: "追问限额和默认开通项目", nextNodeId: "finish", feedback: "这句完整、有效，能把关键坑堵住。", tone: "good", appendToScript: "我再确认一下线上转账限额是多少，另外默认会不会开通理财、短信提醒或其他服务？" },
          { id: "bank-f", label: "觉得问太多不好意思，就不问了", nextNodeId: "finish", feedback: "新手最容易卡在这里，但真正吃亏往往也在这里。", tone: "okay", appendToScript: "那先这样吧。" },
        ],
      },
      {
        id: "finish",
        speaker: "system",
        title: "推荐完整话术",
        message: "更稳妥的说法是：先说明自己第一次办理，再按“材料 - 费用 - 限额 - 默认开通项目”的顺序问清。你不是麻烦，而是在避免后续反复跑。",
        options: [],
      },
    ],
  },
  {
    id: "rent-simulator",
    slug: "rent-simulator",
    title: "租房和房东沟通",
    summary: "练习怎么问价格、押金、水电和维修责任，不绕、不怂。",
    relatedScenarioSlug: "how-to-rent-house",
    goals: [
      { id: "price", label: "问价格", openingLine: "你好，我想先确认一下这套房除了房租外还有哪些费用。", successLine: "先把总成本问清，比只看月租稳多了。" },
      { id: "deposit", label: "问押金", openingLine: "我还想确认一下押金怎么退、一般多久退回来。", successLine: "押金规则越早问越好。" },
      { id: "utility", label: "问水电", openingLine: "水电是按民用还是商业收费？这边平时怎么结算？", successLine: "水电是租房里最容易被忽略的成本。" },
    ],
    nodes: [
      {
        id: "start",
        speaker: "other",
        title: "房东回应",
        message: "房东：你想了解哪方面？房子挺好租的，合适就尽快定。",
        options: [
          { id: "rent-a", label: "直接问总费用包含什么", nextNodeId: "deposit", feedback: "先问费用范围很对，能把节奏拉回你这边。", tone: "good", appendToScript: "我想先确认一下，除了房租以外，物业、水电、网费这些分别怎么算？" },
          { id: "rent-b", label: "先说自己再想想", nextNodeId: "finish", feedback: "还没问清楚就退，会错过关键信息。", tone: "okay", appendToScript: "我再想想吧。" },
        ],
      },
      {
        id: "deposit",
        speaker: "other",
        title: "房东继续说",
        message: "房东：押一付一/押一付三都可以，水电这些到时候再说。",
        options: [
          { id: "rent-c", label: "继续追问押金退回规则", nextNodeId: "utility", feedback: "对，押金和退租规则不能含糊。", tone: "good", appendToScript: "我想把押金和退租条件先确认清楚：退租提前多久说、押金一般什么时候退、哪些情况会扣？" },
          { id: "rent-d", label: "觉得对方不耐烦，就先不问了", nextNodeId: "finish", feedback: "这一步收住了，后面最容易吃亏。", tone: "risky", appendToScript: "行，那到时候再说。" },
        ],
      },
      {
        id: "utility",
        speaker: "other",
        title: "房东催促决定",
        message: "房东：你要是想定，可以先交个定金，其他细节都好说。",
        options: [
          { id: "rent-e", label: "先拒绝定金，继续问水电和维修", nextNodeId: "finish", feedback: "这句很稳，先信息透明，再谈决定。", tone: "good", appendToScript: "我先把水电收费和维修责任问清楚，再决定是否定。现在先不交定金。" },
          { id: "rent-f", label: "怕房子没了，先交定金再说", nextNodeId: "finish", feedback: "最容易被“先定下来”带跑，后面反而更被动。", tone: "risky", appendToScript: "那我先交定金吧。" },
        ],
      },
      {
        id: "finish",
        speaker: "system",
        title: "推荐完整话术",
        message: "更稳妥的顺序是：先问总费用，再问押金和退租，最后问水电与维修。信息不透明时，先不交定金是正常操作。",
        options: [],
      },
    ],
  },
  {
    id: "hospital-simulator",
    slug: "hospital-simulator",
    title: "去医院挂号怎么问",
    summary: "不知道挂什么科的时候，练习怎么向导诊台和医生说清楚。",
    relatedScenarioSlug: "go-to-hospital",
    goals: [
      { id: "which-dept", label: "问挂哪个科", openingLine: "你好，我是第一次自己来看病，想问一下我这种情况先挂哪个科。", successLine: "先描述症状，不急着自己诊断。" },
      { id: "how-pay", label: "问缴费流程", openingLine: "你好，我想确认一下挂号和后续检查一般怎么缴费。", successLine: "第一次来医院，流程比逞强更重要。" },
    ],
    nodes: [
      {
        id: "start",
        speaker: "other",
        title: "导诊台",
        message: "导诊：你哪里不舒服？",
        options: [
          { id: "hosp-a", label: "描述症状和持续时间", nextNodeId: "doctor", feedback: "非常对，症状比猜病名更有用。", tone: "good", appendToScript: "我主要是 ____，已经持续 ____，还伴随 ____，想问一下先挂哪个科合适。" },
          { id: "hosp-b", label: "直接说自己可能得了某个病", nextNodeId: "doctor", feedback: "可以说猜测，但别只说猜测。", tone: "okay", appendToScript: "我怀疑自己是 ____。" },
        ],
      },
      {
        id: "doctor",
        speaker: "other",
        title: "导诊继续追问",
        message: "导诊：有发烧、过敏，或者正在吃什么药吗？",
        options: [
          { id: "hosp-c", label: "把过敏、发烧和用药情况一起说", nextNodeId: "finish", feedback: "这样最完整，能减少你挂错和重复解释。", tone: "good", appendToScript: "有/没有发烧，过敏情况是 ____，现在正在吃 ____。" },
          { id: "hosp-d", label: "记不清，就说应该没有", nextNodeId: "finish", feedback: "不确定时就说不确定，别为了快随便答。", tone: "risky", appendToScript: "应该没有吧。" },
        ],
      },
      {
        id: "finish",
        speaker: "system",
        title: "推荐完整话术",
        message: "医院里最稳妥的表达是“我哪里不舒服、从什么时候开始、现在最明显的症状是什么、有没有发烧过敏和用药”。信息越清楚，流程越顺。",
        options: [],
      },
    ],
  },
  {
    id: "courier-simulator",
    slug: "courier-simulator",
    title: "快递丢了怎么投诉",
    summary: "练习维权时怎么把重点说到位，不被一句“再等等”带走。",
    relatedScenarioSlug: "courier-lost-claim",
    goals: [
      { id: "register", label: "登记丢件", openingLine: "你好，我这个订单已经超过正常时效，想登记丢件并确认处理流程。", successLine: "先把诉求说清，处理才有起点。" },
      { id: "ask-standard", label: "问赔偿标准", openingLine: "我想确认一下这单如果确认丢失，赔偿标准是按什么算。", successLine: "赔偿标准一定要主动问。" },
    ],
    nodes: [
      {
        id: "start",
        speaker: "other",
        title: "客服回应",
        message: "客服：麻烦再等等，我们这边还在核实。",
        options: [
          { id: "c-a", label: "要求明确处理时限和工单号", nextNodeId: "finish", feedback: "对，别只接受一句“再等等”。", tone: "good", appendToScript: "可以，请帮我登记工单，并明确告诉我回复时限和负责人。" },
          { id: "c-b", label: "那我再等等吧", nextNodeId: "finish", feedback: "这句太容易被无限拖延。", tone: "risky", appendToScript: "那我等你们消息。" },
        ],
      },
      {
        id: "finish",
        speaker: "system",
        title: "推荐完整话术",
        message: "维权时要把三件事说出来：订单和问题、你的诉求、处理时限。这样对话才不会一直空转。",
        options: [],
      },
    ],
  },
  {
    id: "interview-simulator",
    slug: "interview-simulator",
    title: "面试自我介绍模拟",
    summary: "练习开场的第一分钟，避免讲太散或者太空。",
    relatedScenarioSlug: "interview-self-introduction",
    goals: [
      { id: "intro", label: "一分半自我介绍", openingLine: "你好，我叫____，目前是____。", successLine: "结构比辞藻重要。" },
    ],
    nodes: [
      {
        id: "start",
        speaker: "other",
        title: "面试官提问",
        message: "面试官：请你先简单介绍一下自己。",
        options: [
          { id: "i-a", label: "先说身份，再说相关经历", nextNodeId: "finish", feedback: "这个顺序很稳。", tone: "good", appendToScript: "你好，我叫____，目前是____。和这个岗位最相关的经历主要有两段：____。" },
          { id: "i-b", label: "先说自己性格很开朗很努力", nextNodeId: "finish", feedback: "不算错，但信息密度太低。", tone: "okay", appendToScript: "我性格开朗，做事认真负责。" },
        ],
      },
      {
        id: "finish",
        speaker: "system",
        title: "推荐完整话术",
        message: "更稳的结构是：你是谁、做过什么、为什么匹配这个岗位。先给事实，再给判断。",
        options: [],
      },
    ],
  },
  {
    id: "probation-simulator",
    slug: "probation-simulator",
    title: "遇到不合理试用期怎么回应",
    summary: "练习在不撕破脸的前提下，把工资、考核和转正规则问清楚。",
    relatedScenarioSlug: "what-is-probation",
    goals: [
      { id: "ask-standard", label: "问转正规则", openingLine: "我想先确认一下试用期考核和转正标准。", successLine: "标准越清楚，你越不容易被动。" },
      { id: "ask-salary", label: "问试用期工资", openingLine: "我也想确认一下试用期工资和转正后的口径。", successLine: "工资问题提早问，比事后追着问更稳。" },
    ],
    nodes: [
      {
        id: "start",
        speaker: "other",
        title: "HR 回应",
        message: "HR：试用期先干着看，后面表现好自然会转正。",
        options: [
          { id: "p-a", label: "继续追问标准和时间点", nextNodeId: "finish", feedback: "很稳，礼貌但不含糊。", tone: "good", appendToScript: "我理解，我想再确认一下具体的考核维度、反馈时间点和转正流程，这样我也更好对齐预期。" },
          { id: "p-b", label: "怕显得较真，就不问了", nextNodeId: "finish", feedback: "这里收住，后面就更容易被动。", tone: "risky", appendToScript: "好的，那我先做着看。" },
        ],
      },
      {
        id: "finish",
        speaker: "system",
        title: "推荐完整话术",
        message: "面对模糊试用期，最稳的做法不是对抗，而是把“标准、时间、工资口径”问成清单。",
        options: [],
      },
    ],
  },
];

const popularScenarios = [...scenarios]
  .sort((left, right) => right.popularityScore - left.popularityScore)
  .slice(0, 6);

const starterScenarios = [...scenarios]
  .sort((left, right) => right.starterPriority - left.starterPriority)
  .slice(0, 6);

const emergencyScenarios = [...scenarios]
  .filter((scenario) => scenario.emergencyLevel > 0)
  .sort((left, right) => right.emergencyLevel - left.emergencyLevel || right.popularityScore - left.popularityScore)
  .slice(0, 6);

export const homeFeedSections: HomeFeedSection[] = [
  {
    id: "popular",
    title: "今日推荐",
    description: "第一次上手社会生活时，最容易马上遇到的高频场景。",
    items: popularScenarios,
  },
  {
    id: "starter",
    title: "新手必学",
    description: "先把这些学了，后面很多小事就不会突然慌。",
    items: starterScenarios,
  },
  {
    id: "emergency",
    title: "紧急场景",
    description: "遇到这些情况时先别慌，先照着做关键动作。",
    items: emergencyScenarios,
  },
];
