#!/usr/bin/env tsx
/**
 * 造血引擎：从 PostgreSQL 提取错题本，生成 Vitest 测试用例
 * 
 * 工作流程：
 * 1. 拉取状态为 PENDING 或 RESOLVED 的争议案例
 * 2. 构造 TypeScript 测试文件
 * 3. 写入 lib/engine/__tests__/fixtures/real-cases.ts
 * 4. 可选：标记为已同步
 * 
 * 执行：npm run sync:disputed
 */

import { PrismaClient } from '@prisma/client';
import fs from 'fs';
import path from 'path';

const prisma = new PrismaClient();

async function syncDisputedCases() {
  console.log('🔍 开始从云端抓取待处理的争议案例...\n');

  // 1. 只拉取状态为 PENDING 或 RESOLVED 的案例
  const cases = await prisma.disputedCase.findMany({
    where: { 
      status: { in: ['PENDING', 'RESOLVED'] },
      syncedToTest: false, // 只拉取未同步的
    },
    orderBy: { createdAt: 'desc' },
  });

  if (cases.length === 0) {
    console.log('✅ 当前没有新的争议案例。引擎运转良好。');
    return;
  }

  console.log(`📦 发现 ${cases.length} 个待同步案例\n`);

  // 2. 构造 TypeScript 文件内容
  let fileContent = `/**
 * ⚠️ 自动生成的错题本测试用例 (Generated by sync:disputed)
 * 
 * 这些案例来源于真实用户的负面反馈，
 * 经过人工确认后标记为 RESOLVED，
 * 用于确保引擎不会重复犯同样的错误。
 * 
 * 最后同步时间: ${new Date().toLocaleString()}
 * 案例数量: ${cases.length}
 */

import type { EvaluationInput } from '@/lib/engine/types';

export interface DisputedTestCase {
  id: string;
  name: string;
  input: EvaluationInput;
  verdictIssued: string;
  expectedVerdict: string;
  feedback: string;
  engineVersion: string;
  disputedAt: string;
}

export const realDisputedCases: DisputedTestCase[] = [
`;

  // 3. 遍历拼接数据
  for (const c of cases) {
    let inputObj: any = {};
    try {
      inputObj = JSON.parse(c.rawInput);
    } catch {
      console.warn(`⚠️  案例 ${c.id} 的 rawInput 解析失败，使用空对象`);
    }

    // 将 JSON 重新格式化为优雅的 TS 对象字符串
    const inputStr = JSON.stringify(inputObj, null, 2)
      .replace(/"([^"]+)":/g, '$1:')  // 去掉引号
      .replace(/"/g, "'");  // 单引号更 TS 风格

    fileContent += `  {
    id: '${c.id}',
    name: 'Case ${c.id.slice(-6)}: ${(c.userFeedback || '无吐槽').substring(0, 30).replace(/'/g, "\\'")}',
    input: ${inputStr} as EvaluationInput,
    verdictIssued: '${c.verdictIssued}',
    expectedVerdict: '${c.correctedVerdict || 'TODO: 人工确认'}',
    feedback: '${(c.userFeedback || '').replace(/'/g, "\\'")}',
    engineVersion: '${c.engineVersion}',
    disputedAt: '${c.createdAt.toISOString()}',
  },
`;
  }

  fileContent += `];

/**
 * 获取指定引擎版本的争议案例
 */
export function getCasesByVersion(version: string): DisputedTestCase[] {
  return realDisputedCases.filter(c => c.engineVersion === version);
}

/**
 * 获取已确认预期判决的案例（可用于回归测试）
 */
export function getConfirmedCases(): DisputedTestCase[] {
  return realDisputedCases.filter(c => 
    c.expectedVerdict && 
    c.expectedVerdict !== 'TODO: 人工确认'
  );
}
`;

  // 4. 写入本地测试文件
  const fixturesDir = path.join(process.cwd(), 'lib', 'engine', '__tests__', 'fixtures');
  
  // 确保目录存在
  if (!fs.existsSync(fixturesDir)) {
    fs.mkdirSync(fixturesDir, { recursive: true });
  }
  
  const targetPath = path.join(fixturesDir, 'real-cases.ts');
  fs.writeFileSync(targetPath, fileContent, 'utf-8');

  console.log(`🔥 成功生成 ${cases.length} 个真实踩坑用例！`);
  console.log(`👉 文件位置: ${targetPath}\n`);

  // 5. 标记为已同步
  const caseIds = cases.map(c => c.id);
  await prisma.disputedCase.updateMany({
    where: { id: { in: caseIds } },
    data: { 
      syncedToTest: true,
      status: 'SYNCED',
      testFixtureId: `batch-${Date.now()}`,
    },
  });

  console.log(`🏷️  已标记 ${caseIds.length} 个案例为 SYNCED\n`);
  
  console.log('🎯 下一步:');
  console.log('   npm run test              # 运行全量测试');
  console.log('   npm run test:disputed     # 只跑争议案例测试');
}

syncDisputedCases()
  .catch(e => {
    console.error('❌ 同步失败:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
